### ISSUE TITLE
results of calculateDiffMeth() for methDiffDB are to same objects 

### ISSUE THREAD

**Issue by alexg9010** [al2na/methylKit#103]
the issue 1 is because the flatfile database is overwritten, you can see that it writes out to the same filename methylDiff_e66b53b34fb6.txt.bgz in each case.

> myDiff_X.1_DB=calculateDiffMeth(meth_X.1_DB)
two groups detected:
 will calculate methylation difference as the difference of
treatment (group: 1) - control (group: 0)
compressing the file with bgzip...
making tabix index...
flatfile located at: /Users/uname/sandbox/methylDB_diffMeth_bug/methylDB 2018-03-11 Gx2/methylDiff_e66b53b34fb6.txt.bgz
> myDiff_X.1_MA_DB=calculateDiffMeth(meth_X.1_DB, covariates = maternalage)
two groups detected:
 will calculate methylation difference as the difference of
treatment (group: 1) - control (group: 0)
compressing the file with bgzip...
making tabix index...
flatfile located at: /Users/uname/sandbox/methylDB_diffMeth_bug/methylDB 2018-03-11 Gx2/methylDiff_e66b53b34fb6.txt.bgz

You can avoid it by adding an argument to make sure results are written to different files, although we should consider changing this behaviour. Different calculateDiffMeth results might be stored in different tabix files (I will check with Alex). But in this case, only the covariates are changing and the function is still applied on the same methylBase object. 
#Creation of methylDiffDB w/o covariates

myDiff_X.1_DB=calculateDiffMeth(meth_X.1_DB)

#creation of methylDiffDB w/ covariates 

myDiff_X.1_MA_DB=calculateDiffMeth(meth_X.1_DB,
                                   covariates = maternalage,
                                   suffix="MA_DB")

**Comment by al2na** [comment]
what should we do about this? is this a design thing or a bug ?

**Comment by alexg9010** [comment]
So the problem is this section here: https://github.com/al2na/methylKit/blob/master/R/methylDBFunctions.R#L1391-L1394 where I just replace the prefix of the original file. Considering that people will use the input multiple times to calculate different results we should change this behavior.

**Comment by al2na** [comment]
ok, lets do it

**Comment by alexg9010** [comment]
This should be solved here https://github.com/al2na/methylKit/commit/b42a46089163c80ffc57fed1000d33f4d135aff9
