### ISSUE TITLE
processBismarkAln error

### ISSUE THREAD

**Issue by kpatankar** [al2na/methylKit#107]
I am running processBismarkAln() function on a bam file obtained after bismark alignment. The bam file generated for paired-end nextseq data. The Command I used is as follows.

`processBismarkAln(location = "/path/to/bam/file", sample.id = "SampleNo", assembly = "hg38", save.folder = NULL, save.context = c("CpG"), read.context = "CpG", nolap = FALSE, mincov = 10, minqual = 20, phred64 = FALSE, save.db = FALSE)` 

I am getting the following error

> Error in methCall(read1 = location, type = "bam", nolap = nolap, minqual = minqual,  : 
   the value of --read1 argument does not point to an existing file

Can you please tell me how to resolve this error.

Thanks in advance!!!

**Comment by kpatankar** [comment]
Thank you!!! I checked and mentioned the file name at the end of path in location and it worked. 
My next question is I am trying to find methylation status of a specific gene from the bismark alignment data using methylkit. I have downloaded the bed file from UCSC genome browser for that particular gene. to find the methylation status of a specific region I am using the following protocol.

[https://www.biostars.org/p/91141/]

Can you guide me if this is the correct way or is there any other way in which I can do this?

Thanks!!

**Comment by alexg9010** [comment]
If you want to get a genome wide overview of the methylation status, follow the user guide to do the [annotation](https://www.bioconductor.org/packages/devel/bioc/vignettes/methylKit/inst/doc/methylKit.html#4_annotating_differentially_methylated_bases_or_regions). 

Now if you want to focus on a specific region, there are different ways to proceed: 

- either use the `selectByOverlap` function to get a methylKit object overlapping your regions of interest
- or coerce your methylKit object to GRanges using `as(obj,"GRanges")` and go on using GenomicRanges functionality

**Comment by kpatankar** [comment]
Hi,

Thank You for the suggestion. I am following the annotation protocol on the link which you sent:

Here are the commands:
```
myobj = methRead("C:/Users/kalyani_patankar/Desktop/S5/methCall/S5_CpG.txt", sample.id = "S5", assembly = "hg38", context = "CpG")

library(genomation)

gene.obj = readTranscriptFeatures(location = "C:/Users/kalyani_patankar/Desktop/S5/DMPK.bed")

annotate.WithGenicParts(as(myobj, "GRanges"), gene.obj)
```
I am getting the following error:

> Error in annotate.WithGenicParts(as(myobj, "GRanges"), gene.obj) : 
>   unused arguments (as(myobj, "GRanges"), gene.obj)

I have only one sample and thus don't want to create `myDiff25p` object. I wish to use `myobj` which is a `methylRawList` object.

How can I resolve this error?

Thanks again for all the help.

**Comment by alexg9010** [comment]
The function `annotate.WithGenicParts` is deprecated, you should use genomation function `annotateWithGeneParts` to do this.
