### ISSUE TITLE
improve documentation around pipeline argument for the read() function

### ISSUE THREAD

**Issue by igordot** [al2na/methylKit#11]
From what I understand, the only Bismark output that methylKit works with is the SAM file and that is processed with `read.bismark`. However, the documentation for `read` has a `pipeline` argument with one of the options as "bismark". What sort of file is expected there?

I also saw a discussion about using Bismark cytosine reports (https://groups.google.com/forum/#!topic/methylkit_discussion/0s1DLTWsLyM). Apparently, they can be converted by simply using the code:
`awk '{OFS="\t";if($4+0 > 0 || $5+0 >0 ) print $1,$2,$3,$4/($4+$5),$4+$5;}' cytosineReport.txt > outputForMethylKit`
That file will work with `read`, but it requires a custom pipeline setting, so I am still not sure what the "bismark" pipeline setting is for.

**Comment by al2na** [comment]
pipeline argument can be "bismark" or "amp" strings, in which case the function expects a tabular output format shown in the webpage.  "amp" was a pipeline used in 2012 Plos genetics paper, publicly available in googlecode. These are implemented before bismark had a cytosine report option to denote our own processing way of bismark sam files, so these argument values has nothing to do with that.

**Comment by igordot** [comment]
I ended up using a custom pipeline setting and it's working.

As you mention, "amp" pipeline is shown on the webpage. However, there is no explanation of the "bismark" pipeline anywhere.

**Comment by al2na** [comment]
I will try to improve the documentation on this. If your pipeline is online
and usable, I can give a link from methylKit webpabe.

**Comment by igordot** [comment]
I just meant the `pipeline` parameter of the `read` function. Based on that awk command, it would be:
```
pipeline=list(fraction=T, chr.col=1, start.col=2, end.col=2, strand.col=3, freqC.col=4, coverage.col=5),
```
My main concern was that "amp" is documented, but "bismark" is not. There is no indication anywhere that any of the Bismark output is compatible with the `read` function, but that `pipeline` option must exist for a reason.

**Comment by al2na** [comment]
as I wrote bismark output is probably not compatible with methylkit without further processing. I don't understand what more can be done other than improve the documentation

**Comment by igordot** [comment]
So `read` with `pipeline="bismark"` is identical to `read.bismark`?

**Comment by al2na** [comment]
read.bismark produces text files either written in temp dir or user defined
location, when re-reading those text files pipeline="bismark" should be
used, Or that was the idea. If you have a custom pipeline that produces the
location and methylation information then you can use the
pipeline=list(...) format. This gives you flexibility to deal with custom
text files as long as they conform to a general structure described in the
doc. Unfortunately, last time I checked native Bismark output didn't
conform to that structure, it was missing a column, so they have to be
processed further. please see the Q & A forum. That is a better venue for
such questions

**Comment by igordot** [comment]
Everything makes sense now. Thanks for clearing it up.

**Comment by al2na** [comment]
this is done as of v0.9.6
