### ISSUE TITLE
calculateDiffMeth() saves a tabix object with a non-random name

### ISSUE THREAD

**Issue by katwre** [al2na/methylKit#111]
I ran calculateDiffMeth() with a methylBaseDB object as an input with different parameters 5 times and every time it saved it to the same file (e.g. methylDiff_9c4f718e0491.txt.bgz.bgz).

Now I know that I can use suffix argument to control better names of output files. So with suffix argument
it saves it now as e.g. methylDiff_9c4f718e0491_treatment_2.txt.bgz, so besides my suffix treatment_2 there is still a 13-character "random" string added before my suffix, is it intentional?

Cheers,
Kasia

**Comment by alexg9010** [comment]
The random string at the second position stems from the creation of the methyBaseDB object. 
So basically what happened was that you created a methylBaseDB object with associated tabix file `methylBase_9c4f718e0491.txt.bgz` and then when you run calculateDiffMeth() a new file is created 
 renamed `methylDiff_9c4f718e0491.txt.bgz`. Then if you add a suffix, you add it to this previous construct, namely  `methylDiff_9c4f718e0491_treatment_2.txt.bgz` . 

So the random string is already part of the filename and not newly created.
