### ISSUE TITLE
Calculate Methylation of Promoter Region

### ISSUE THREAD

**Issue by kpatankar** [al2na/methylKit#112]
Hi,

I want to calculate the percentage of methylation in promoter region of DMPK gene. I have read my sample alignment into a `methylRaw` object using `processBisMarkAln` function. I have also downloaded the coordinates of promoter region for DMPK gene using UCSC table browser. I looked into `perMethylation()` function which takes in a `methylBase` object. according to the manual, `methylBase` object is the object with comparisons of all samples. I have only one sample to analyse. How can i use the `MethylRaw` obj to calculate percentage of methylation?

I tried this following approach to calculate percentage of methylation in promoter region:
```
myobj = processBismarkAln("S1_pe.deduplicated_sorted.bam", assembly = "hg38", sample.id = "S1", read.context = "CpG", save.folder = "S1/methCall")

```

`gene.obj = readTranscriptFeatures("dmpk_gene")`

`promoters=regionCounts(myobj , gene.obj$promoters)
`
This produces promoter dataframe as follows:

![image](https://user-images.githubusercontent.com/24659373/40673205-bd1368b6-6336-11e8-98eb-0d5bdfd18e0d.png)

Can I calculate 

`perc_of_methylation = (number of C's/ (num of C's + num of T's))*100`

So, percentage methylation for promoter will be 

`(404/(404+1501))*100 = 21.20%`

Please let me know if this approach is correct?

**Comment by al2na** [comment]
yes, this is one way to do it, and would say most common way to do this
