### ISSUE TITLE
methylKit:::readMethylBaseDB requires a vector and not a list for the argument sample.ids

### ISSUE THREAD

**Issue by alexg9010** [al2na/methylKit#124]
https://groups.google.com/forum/#!topic/methylkit_discussion/vK5CrQcnSLM

**Comment by alexg9010** [comment]
These functions are actually not exported and actually rather intended for internal use. 
See comments (https://github.com/al2na/methylKit/blob/master/R/methylDBClasses.R#L453)
But to make them consistent with the methRead function I can make them accept lists of characters and vectors of characters for the sampleID.

**Comment by al2na** [comment]
is there an equivalent you can recommend for the users ? that uses lists?
that the problem is solved maybe

**Comment by alexg9010** [comment]
Right now there is no exported function to read other than methylRawDB files (via methRead).

Actually I will have to write such an equivalent once the taxi header stuff is done.
