### ISSUE TITLE
Adding covariates

### ISSUE THREAD

**Issue by Camethyleabergen** [al2na/methylKit#128]
Hi Altuna,

I come today with two questions about covariates into BSseq data 

- in your tutorial you mention : 

>  In this case, we will test if full model (model with treatment and covariates) is better than the model with the covariates only. If there is no effect due to the treatment (sample groups), the full model will not explain the data better than the model with covariates only. In calculateDiffMeth, this is achieved by supplying the covariates argument in the format of a data.frame. 
I definitely get a new object, but by what mean can I get to know if it explains the data "better" ? I guess I'm lacking there a methodologic point.

- is it possible to have multiple covariates? 
I tried with a data.frame with 2 columns, or a vector of data.frame, but it seems to accept only one covariate at a time: can you confirm it or I misuse it ? 
when i try : 
> cov_two_factorscovariates
  pm_time_min age_years
1         340        89
2         270        81
3         435        95
sim.methylBase=dataSim(replicates=3,sites=10000,
                        treatment=sapply(file_treatment,c),
                        covariates=cov_two_factorscovariates,
                        sample.ids=sapply(file_list_name,c))
Error in b1 * x : non-numeric argument to binary operator

And then again, I think I have issues understanding how a simulated data (how is it simulated? I can't find it on your paper from Genome Biology (2012) ) can be analysed with the "real" dataset ? 
Would you have any reference paper or ressources to make me understand the process there?

Best,

**Comment by katwre** [comment]
Hi Camethyleabergen,
Are you sure that your data.frame `cov_two_factorscovariates` contains only numeric values and not e.g. factors?
Check out Details in dataSim() documentation (you can see it after typing `?dataSim` in R console). In `dataSim` read coverage is modeled by a binomial distribution and methylation background follows a beta distribution. You might be also interested in checking out our paper (of @al2na , @alexg9010 and mine) https://www.sciencedirect.com/science/article/pii/S0168165617315936?via%3Dihub, maybe it can help you to understand how simulated data is created (chapter 4.1) and you can find there also some examples using simulated data (https://github.com/BIMSBbioinfo/Strategies_for_analyzing_BS-seq/blob/master/diff_meth_tools/compareUsingSimulated.Rmd#simulation) and on real data (https://github.com/BIMSBbioinfo/Strategies_for_analyzing_BS-seq/blob/master/diff_meth_tools/compareUsing_CTCF_RRBS_pairsCelllines.Rmd)

Cheers,
Kasia
