### ISSUE TITLE
methylKit unite function error

### ISSUE THREAD

**Issue by katwre** [al2na/methylKit#130]
https://groups.google.com/forum/#!topic/methylkit_discussion/gw9PfHUPlOA

There is a bug in `unite()` on a methylRawDB with destrand=TRUE, locations are written in a scientific notation, e.g. 6e+5 instead of 600000 and an error occurs when making the tabix index.

**Comment by al2na** [comment]
i think this occurs when writing out to the files, if the coordinate has
many zeros towards the end R automatically writes it out in scientific
notation.
I dealt with this in the bedgraph function as shown here:
https://github.com/al2na/methylKit/blob/master/R/bedgraph.R#L116 I'm not
sure if that is the most elegant solution.
