### ISSUE TITLE
not enough alignments that pass coverage and phred score thresholds to calculate conversion rates

### ISSUE THREAD

**Issue by runningsnail2333** [al2na/methylKit#148]
hi 
i meet this problem and don't know how to solve it 
```
my.rawdata=processBismarkAln(location = "test_sorted.bam",
+                             sample.id = "Me-1",
+                             assembly = "hg19",
+                             read.context = "CpG",save.folder = getwd(),mincov=10,minqual=20)
```
Error in methCall(read1 = location, type = "bam", nolap = nolap, minqual = minqual,  : 
  
not enough alignments that pass coverage and phred score thresholds to calculate conversion rates
 EXITING....

i check my bam 
![微信图片_20190313095900](https://user-images.githubusercontent.com/26783050/54248180-a3ea2780-4576-11e9-8a7d-19feed9fc111.png)

**Comment by al2na** [comment]
Did you try to decrease my mincov ?

**Comment by runningsnail2333** [comment]
sorry for reply late, thanks al2na~ i change the mincov to 1 and it can work . thanks very much!
