### ISSUE TITLE
datasim for one rep should return methylRaw

### ISSUE THREAD

**Issue by alexg9010** [al2na/methylKit#149]
Right now if I call dataSim with one rep I get methylBase object. There should be an option to make this a methylRaw .

```
> (myMethRaw <- dataSim(replicates = 1, sites = 1e3, treatment = c(0)))
methylBase object with 1000 rows
--------------
   chr start end strand coverage1 numCs1 numTs1
1 chr1     1   2      +        32      0     32
2 chr1     2   3      +        67     63      4
3 chr1     3   4      +        30      0     30
4 chr1     4   5      +        75      0     75
5 chr1     5   6      +       550    330    220
6 chr1     6   7      +        48      1     47
--------------
sample.ids: ctrl1 
destranded FALSE 
assembly: hg18 
context: CpG 
treament: 0 
resolution: base 
```

**Comment by alexg9010** [comment]
Could be as easy as: 

```
methylBase2Raw <- function(object) {
  
  object = new("methylRaw",getData(object),
                sample.id=object@sample.ids,
                assembly=object@assembly,
                context=object@context,
                resolution=object@resolution)
  colnames(object) <- gsub(pattern = "1","",colnames(object))
  return(object)
}
```

**Comment by al2na** [comment]
I wouldn't write this function exposed to the user, but i would just invoke
it within datasim when replicates =1.
But I'm not sure who would want to simulate one replicate only. Did you
come across such a case ?

**Comment by alexg9010** [comment]
You are right it makes more sense to have this inside the function only.

The only use case would be to actually create methylRaw objects for test
cases, which is only useful for us. But I was thinking that having a
methylBase object with one rep does not make sense, so we could give it the
class that actually stores single samples.

Sent from mobile.

Am Do., 4. Apr. 2019, 21:46 hat Altuna Akalin <notifications@github.com>
geschrieben:

> I wouldn't write this function exposed to the user, but i would just invoke
> it within datasim when replicates =1.
> But I'm not sure who would want to simulate one replicate only. Did you
> come across such a case ?
>
>
>
> On Thu, Apr 4, 2019 at 12:26 PM Alexander Gosdschan <
