### ISSUE TITLE
feature request: read input from bismark sorted bams

### ISSUE THREAD

**Issue by avilella** [al2na/methylKit#15]
This is a feature request on the development branch of methylkit.

As far as I can tell from the documentation, methylkit can read the necessary input from bismark output files by running the `read.bismark()` method, which currently calls a perl script that seeks `.sam.gz` files sorted by chromosome-position and transforms the content of each `.sam.gz` into the correct input for methylKit.

I have seen on Trello there is the intention to integrate bamtools c++ method calls, I presume it overlaps with this feature request: for methylkit to read in chromosome-position sorted bams from Bismark.

Thx

**Comment by al2na** [comment]
Yes, we have plans to do this. I don't know when this will be realized
though

**Comment by al2na** [comment]
this is done in the newer versions (0.9.6 and above)
