### ISSUE TITLE
Updated FAQ

### ISSUE THREAD

**Issue by alexg9010** [al2na/methylKit#150]
Hi @al2na,

I updated the FAQ section of the vignette, but wanted to check with you first wether this is okay, before I push to Bioc.

Maybe you could have a short look: 
https://github.com/al2na/methylKit/blob/2159a840c98113ac1d6768bbf5e2d1f1dcf1eac3/vignettes/methylKit.Rmd#L911-L931

**Comment by al2na** [comment]
sure, there is a typo though: " as such dos not" should be " as such does
not"

Best,
Altuna
