### ISSUE TITLE
feature request: script to transform bismark methylation output into methylKit input

### ISSUE THREAD

**Issue by avilella** [al2na/methylKit#16]
This is a feature request against the development branch of methylKit:

As far as I can tell from the Illumina BaseSpace MethylKit, one can use methylation calls from bismark methylation extractor as input for methylkit. I presume there is a data transformation process between the bismark output files and the required methylKit input format. I have seen a similar data transformation described for BSMAP here: http://zvfak.blogspot.co.uk/2012/10/how-to-read-bsmap-methylation-ratio.html

This is a feature request to implement this data transformation of bismark methylation extractor files into methylkit input files. 

NOTE: It may be that once the data transformation is identified, it's best for @FelixKrueger to have such code on bismark's side.

Thx

**Comment by al2na** [comment]
I think we should write a separate function to do this, named something
line read.bismarkExtractor() or smthing similar, rather than trying to
transform bismark output

**Comment by avilella** [comment]
See an example output set of files from bismark_methylation_extractor:

https://cloud.curoverse.com/collections/download/qr1hi-4zz18-sl6u4104waj4z2q/5171q6qushlbs31edpkhnntxgi6xwykgi94ya60fw45mkg8a0j/

**Comment by avilella** [comment]
Would this work as a script to transform one file into another?

https://github.com/avilella/methylKit/blob/master/exec/bismark_cpg_report2mycpg.pl

@al2na @FelixKrueger

**Comment by al2na** [comment]
Hi @avilella,
I wrote a couple of functions to read Bismark coverage and cytosine report files as methylKit objects. They are not part of the package yet but you can use the functions via devtools::source_gist()

The functions are here:
https://gist.github.com/al2na/4839e615e2401d73fe51

The functions can read multiple files at a time or just one file. They require R.utills package in addition to other methylKit dependencies. There is some inline documentation in the gist.
```
devtools::source_gist("4839e615e2401d73fe51")

readBismarkCoverage( location,sample.id,assembly="unknown",treatment,
                                    context="CpG",min.cov=10)
readBismarkCytosineReport( location,sample.id,assembly="unknown",treatment,
                                    context="CpG",min.cov=10)
```

**Comment by avilella** [comment]
Should the script below work up until completing the `readBismarkCoverage` statement?

```
#!/usr/bin/Rscript
library(methylKit)
args<-commandArgs(TRUE)
devtools::source_gist("4839e615e2401d73fe51")
file.list = list(args[1],args[2],args[3],args[4])
# myobj = read(file.list,sample.id=list("CASE1","CASE2","ctrl1","ctrl2"),assembly="hg38",pipeline="amp",treatment=c(1,1,0,0))
myobj = readBismarkCoverage(file.list,sample.id=list("CASE1","CASE2","ctrl1","ctrl2"),assembly="hg38",treatment=c(1,1,0,0))
pdf(   file="MethylationStats_Sample1.pdf") ; getMethylationStats(myobj[[1]],plot=T,both.strands=T); dev.off()
pdf(   file="MethylationStats_Sample2.pdf") ; getMethylationStats(myobj[[2]],plot=T,both.strands=T); dev.off()
pdf(file="MethylationStats_Reference1.pdf") ; getMethylationStats(myobj[[3]],plot=T,both.strands=T); dev.off()
pdf(file="MethylationStats_Reference2.pdf") ; getMethylationStats(myobj[[4]],plot=T,both.strands=T); dev.off()

meth = unite(myobj)
pdf(file="Meth_CorrelationPlot.pdf"); getCorrelation(meth,plot=T); dev.off()

myDiff=calculateDiffMeth(meth)
# write.table(file="diff.tsv",myDiff)


# gene.obj=read.transcript.features(system.file("/bi/group/cegx/UCSC_database", "refseq.hg38.bed.txt", package = "methylKit"))
# annotate.WithGenicParts(myDiff,gene.obj)
```

I get this error when trying it with 4 "*.bismark.cov.gz" files:

```
Loading required package: methods
Sourcing https://gist.githubusercontent.com/al2na/4839e615e2401d73fe51/raw/cca5bf0b6bbc7ee7422153ab8bed4aaffafeae6e/readBismarkFiles.R
SHA-1 hash of file is 2a467d0722e9c8e4a52b769818ccb757a362ba42
Loading required package: R.utils
Loading required package: R.oo
Loading required package: R.methodsS3
R.methodsS3 v1.7.0 (2015-02-19) successfully loaded. See ?R.methodsS3 for help.
R.oo v1.19.0 (2015-02-27) successfully loaded. See ?R.oo for help.

Attaching package: ‘R.oo’

The following objects are masked from ‘package:methods’:

    getClasses, getMethods

The following objects are masked from ‘package:base’:

    attach, detach, gc, load, save

R.utils v2.2.0 (2015-12-09) successfully loaded. See ?R.utils for help.

Attaching package: ‘R.utils’

The following object is masked from ‘package:utils’:

    timestamp

The following objects are masked from ‘package:base’:

    cat, commandArgs, getOption, inherits, isOpen, parse, warnings

Loading required package: data.table
Error in dirname(pathname) : a character vector argument expected
Calls: readBismarkCoverage ... getReadablePathname -> getReadablePathname.Arguments -> dirname
Execution halted
```

Is there a required step to merge the coverage files and the CytosineReport files once loaded?

**Comment by al2na** [comment]
can you try again? I updated so that it actually works with lists? previously it was only able to work with vector input for location argument.

**Comment by avilella** [comment]
Correct, it now reads in the files but fails to produce the Methylation Stats. See below. Is it possible this is due to needing the coverage *and* the CytosineReport files combined?

```
Read 2214731 rows and 6 (of 6) columns from 0.066 GB file in 00:00:03
Error in hist.default((plus.met), plot = F, ...) : 
  invalid number of 'breaks'
Calls: getMethylationStats -> getMethylationStats -> hist -> hist.default
Execution halted
```

**Comment by al2na** [comment]
The coverage files has no strand so when you put both.strands=T, it throws
an error. If you want, stranded information you should use cytosine report
files.

**Comment by avilella** [comment]
It worked with the other read method, `readBismarkCytosineReport`.

It would be great to include this into the master branch, and make a point
release. Cheers.

**Comment by al2na** [comment]
we will at some point, have to figure out where it goes (probably under
read() function with new arguments ) and do some housekeeping before we
include it to the new release.

**Comment by al2na** [comment]
as of v0.9.6 this is implemeted

**Comment by zyworship** [comment]
Hey dear al2na, I have read the question above , now I use the version 1.1.7, but I don't know how to handle the same problem. I cann't read the bismark_methylation_extract resulet file. after read the dialogue above , I don't get the method to handle it .
Could you please , teach me to read the result file?
another problem , I use processBismarkAln read the sorted sam file, then ,get the methRaw ,but I cann't draw a picture about the getMethylationStats,and getCoverageStats, i just can get the result with plot FALSE ,like this:
getMethylationStats(myobj,plot = FALSE, both.strands = FALSE,labels = TRUE)
methylation statistics per base
summary:
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
   0.00   76.92   88.89   83.05   95.00  100.00
percentiles:
       0%       10%       20%       30%       40%       50%       60%       70%
  0.00000  60.00000  72.72727  80.00000  84.61538  88.88889  91.66667  93.75000
      80%       90%       95%       99%     99.5%     99.9%      100%
100.00000 100.00000 100.00000 100.00000 100.00000 100.00000 100.00000

getCoverageStats(myobj,plot = FALSE, both.strands = FALSE)
read coverage statistics per base
summary:
    Min.  1st Qu.   Median     Mean  3rd Qu.     Max.
   10.00    12.00    14.00    16.52    18.00 14030.00
percentiles:
   0%   10%   20%   30%   40%   50%   60%   70%   80%   90%   95%   99% 99.5%
   10    10    11    12    13    14    15    17    19    22    26    46    75
99.9%  100%
  218 14034

Is there any problem in my file ? or any another question in my command?

**Comment by al2na** [comment]
we can read certain bismark outputs, from the docs for methRead: "Bismark aligner can output methylation information per base in multiple formats. With pipeline='bismarkCoverage', the function reads bismark coverage files, which have chr,start,end, number of cytosines (methylated bases) and number of thymines (unmethylated bases) format. If bismark coverage files are used the function will not have the strand information,so beware of that fact. With pipeline='bismarkCytosineReport', the function expects cytosine report files from Bismark, which have chr,start, strand, number of cytosines (methylated bases) , number of thymines (unmethylated bases),context and trinucletide context format."

Please read the documentation for bismark.

for your other questions read the documentation for the functions you are trying to use, for one thing if you want to get plots from those functions you should set plot=TRUE

**Comment by zyworship** [comment]
thank you answer for my question.


Here is my analyse process :
I use the processBismarkAln read the sorted sam file which out put from bismark aling. the command :processBismarkAln(location=("HLiver_1.clean_bismark_bt2_pe_sort.sam"),sample.id="HLiver",assembly="napar",save.folder=getwd(),save.context="CpG",read.context="CpG")
then it put a HLiver_CpG.txt file. then, I use the methRead to read the HLiver_CpG.txt file into methRaw. command like this : my.methyRaw=methRead(location = "HLiver_CpG.txt",sample.id="HLiver",assembly="napar",dbtype="tabix",pipeline="amp",treatment="test")
then it make two file: methylDB. Dph and Hv4 in the dir 
next I use the  getMethylationStats(my.methyRaw,plot=TRUE,both.strands=FALSE,labels=TRUE) to get the stats about the methRaw. but this output a pdf file , but it's 0, I can't open the file.  : 0 Mar 24 16:27 Rplots.pdf
please help me , I can't handle this problem.
发自网易邮箱大师


On 03/23/2017 15:48，Altuna Akalin<notifications@github.com> wrote：

we can read certain bismark outputs, from the docs for methRead: "Bismark aligner can output methylation information per base in multiple formats. With pipeline='bismarkCoverage', the function reads bismark coverage files, which have chr,start,end, number of cytosines (methylated bases) and number of thymines (unmethylated bases) format. If bismark coverage files are used the function will not have the strand information,so beware of that fact. With pipeline='bismarkCytosineReport', the function expects cytosine report files from Bismark, which have chr,start, strand, number of cytosines (methylated bases) , number of thymines (unmethylated bases),context and trinucletide context format."

Please read the documentation for bismark.

for your other questions read the documentation for the functions you are trying to use, for one thing if you want to get plots from those functions you should set plot=TRUE

**Comment by al2na** [comment]
you might need to call dev.off() after plotting, some info here, seems like
a general R question not specific to methylKit:
http://compgenomr.github.io/book/introduction-to-r.html#plotting-in-r

**Comment by zyworship** [comment]
thank you so much
I try the command as this
>pdf("plots.pdf")
>boxplot(getMethylationStats(my.methyRaw,plot=TRUE,both.strands=FALSE,labels=TRUE))
Read 1000000 rows and 7 (of 7) columns from 0.033 GB file in 00:00:05
Read 1000000 rows and 7 (of 7) columns from 0.033 GB file in 00:00:07
Read 964419 rows and 7 (of 7) columns from 0.032 GB file in 00:00:09
Error in plot.window(xlim = xlim, ylim = ylim, log = log, yaxs = pars$yaxs) :
  need finite 'ylim' values
In addition: Warning messages:
1: In is.na(x) : is.na() applied to non-(list or vector) of type 'NULL'
2: In is.na(x) : is.na() applied to non-(list or vector) of type 'NULL'
3: In is.na(x) : is.na() applied to non-(list or vector) of type 'NULL'
4: In min(x) : no non-missing arguments to min; returning Inf
5: In max(x) : no non-missing arguments to max; returning -Inf
> dev.off()
pdf
  2
then i check the result pdf like this :
although it give a error information but it put a result so happy !!! Is very important about the error?
thank you so much. now check the result 
发自网易邮箱大师


On 03/24/2017 16:50，Altuna Akalin<notifications@github.com> wrote：
you might need to call dev.off() after plotting, some info here, seems like
a general R question not specific to methylKit:
http://compgenomr.github.io/book/introduction-to-r.html#plotting-in-r

**Comment by zyworship** [comment]
Hello Al2na:
    Nowadays, I am using the methylKit to find DMR with my data. My data is 4 test and 4 control, the size of each cytosine_report file is almost 25Gb. I run the methylKit with the R-script file in the attachment. 
    The methylKit is break off at the "tiled.methylRaw = tileMethylCounts(object = pooled.methylBase,win.size = 1000,step.size = 100,cov.bases = 4,mc.cores=2)"  . The log file reveal that the mememory is not enough for the methylKit , although I have 1T mememoris， it can't work at this step. 
    Is there any similar problem you get from the user? 
    Is there any  way to reduce the using of memory.


best wish to you


Zhang Yi




发自网易邮箱大师

**Comment by al2na** [comment]
I haven't seen this error. What is the size of your  pooled.methylBase
object ?
