### ISSUE TITLE
Filter by context if bismark cytosine report is given

### ISSUE THREAD

**Issue by alexg9010** [al2na/methylKit#163]
https://github.com/al2na/methylKit/blob/a22fb817a1c244ccba0491b9289064731c801a30/R/backbone.R#L280

**Comment by asumann** [comment]
Hi Alex,

I can't see this function in the package. How can I use it?

Thanks,
Asuman

**Comment by alexg9010** [comment]
Hi Asuman,

When you use the methread function to read in a cytosine report generated by Bismark or methylDackel,  then we are now filtering for the given context (CpG, CHG, CHH). 

This feature will be available in methylKit starting from version 1.13.4, so will come with the next release of bioconductor (3.11). 

Best,
Alex

**Comment by asumann** [comment]
Many thanks for the quick reply!

It is my first time with methylKit and I will specifically look for C contexts. I assume extracting contexts by awk and running analysis will bring no problem. Can you confirm that?

**Comment by alexg9010** [comment]
Sure, 
Of course you can also preprocess the input files before loading them into methylKit. 
This was the recommended way to do it so far.

**Comment by asumann** [comment]
I got some probably unusual methylation percentage plot for my non-CpG data. They had only one peak at the left end, while CpG data had two peaks at both ends. I suspect maybe I couldn't extarcted non-CpG data correctly.
The example code I used:
```awk '($6 == "CHG")' CysRep1.cov.CX_report.txt > CysRep1.CHG_report.txt```
Can you check it if you have time?

**Comment by alexg9010** [comment]
The command for filtering looks correct to me, but you can easily check by inspecting the output file (CysRep1.CHG_report.txt), as it should only contain CHG in the context column. 

Concerning the plot, the distribution of methylation percentage might look completely different for non-CG compared to CpG methylation, but this is dependent on the organism you are studying. 

In mammals you rarely see methylation on non-CG sites, whereas in plants it is quite common.  


I hope this answered your question, but you might want to ask your more detailed analysis questions via e-mail to methylkit_discussion@googlegroups.com or post a question using the web interface (https://groups.google.com/forum/#!forum/methylkit_discussion).


Best,
Alex

**Comment by asumann** [comment]
You answered perfectly! I suspected that there is anything biased for CG in methylkit. Many thanks!!

Best,
Asuman
