### ISSUE TITLE
Question regarding tiling

### ISSUE THREAD

**Issue by VilainLab** [al2na/methylKit#175]
Hello,
Thanks for the great tool. I have a quick question regarding the validity check for tileMethylCounts function. For this particular experiment I have 9 samples (5 called MORs and 3 called FORS). Now, when I am performing DMR analysis, while I am doing tiling, I am getting the following warning **"object has more than one sample id: only one allowed"**. While reading the data I am reading it based on the default resolution, i.e. base, and filtering it based on criteria defined in the tutorial. Please find attached the code and the output till the filtering. I have 2 questions in this case:
a) Should I ignore this warning?
b) If not is there a special way to handle DMRs?

Please let me know if you have any further questions.

Thanks, 
Surajit
[methylationwarning.txt](https://github.com/al2na/methylKit/files/4010574/methylationwarning.txt)

**Comment by alexg9010** [comment]
Hi Surajit,

I checked your example and was able to reproduce this warning/message. 
You can safely ignore the warning, I will try to silence it. 

Best,
Alex
