### ISSUE TITLE
feature request: ability to ingest SAMPLE.myCpG.txt.gz compressed files

### ISSUE THREAD

**Issue by avilella** [al2na/methylKit#18]
This is a feature request for methylKit:

In order to reduce the disk usage footprint, it would be convenient if mehylkit had a `read` operation from compressed `SAMPLE.myCpG.txt.gz` files. Example:
```
# Uncompressed txt files
file.list = list(args[1],args[2],args[3],args[4])
myobj = read(file.list,sample.id=list("CASE1","CASE2","ctrl1","ctrl2"),assembly="hg38",pipeline="amp",treatment=c(1,1,0,0))
```

Maybe an extra flag that detects the gz extension?

```
file.list = list(args[1],args[2],args[3],args[4])
myobj = read(file.list, compressed_ext=c(".gz",".bz2"),sample.id=list("CASE1","CASE2","ctrl1","ctrl2"),assembly="hg38",pipeline="amp",treatment=c(1,1,0,0))
```
Apologies if this already exists, or if it's a trivial R code modification...

**Comment by al2na** [comment]
this could be, although we were about to switch to data.table::fread() for
reading the files, currently it can't deal with zipped files but you can
pass "zcat methylFile.txt.gz" to the function. Another alternative is
readr::read_table() which can read compressed files with no problem but
seems to have some problems when guessing column classes of "-","+" or ".".
I will wait a bit until either readr or fread gets better .

**Comment by al2na** [comment]
this now works
