### ISSUE TITLE
Is there a way to open saved methylBase object?

### ISSUE THREAD

**Issue by ryansohny** [al2na/methylKit#183]
Hi, Mr. Akalin. I have a short question pretty dumb one. 

Is there a way to open saved methylBase object?

Everytime I do the analysis I need to open the inputs compressing the file with bgzip and making tabix index. 

Thank you
Ryan

**Comment by alexg9010** [comment]
Hi Ryan,

If you want to see what is inside the tabix (.bgz) file, you can just use
gunzip or gzcat  in a Linux terminal, but you maybe want to keep the
original.

But if you want to read a previously created methylBaseDB tabix file into
methylKit, right now you can use the internal
methylKit:::readMethylBaseDB() function. But you still need to provide
object metadata, like sample.ids, etc.

With the next release on Bioconductor we introduce a new functionality,
whereafter you should be able to load the tabix file without any additional
information required.

Hope that answers your question.

Best,
Alex

Sent from mobile.

RYAN SOHN <notifications@github.com> schrieb am Do., 9. Apr. 2020, 08:23:

**Comment by ryansohny** [comment]
Thanks for the quick answer Alex.

Much appreciated it. 

Hope to see the new release soon 

Wish you the best luck!
Ryan
