### ISSUE TITLE
Possible to provide coverage filtered CX_report to methRead?

### ISSUE THREAD

**Issue by npatel22526** [al2na/methylKit#184]
Hello Alex, 

Thank you for the great tools and detailed usage information. 
I have CX_report file from 12 WGBS samples and need to perform analysis but memory is big constrain due to shared environment . Would you kindly advice on which one of below is the most sensible way to perform the analysis ?

1. Split files into CpG, CHH and CHH and process them individually
2. Split files per chromosome
3. Filter for coverage before loading the files , this is I am most interested if it is possible at all
4. Any combination of above

I see that one has to specify "Context" when reading input file. Specifying "Context" is ignoring the remaining sites when loading or loads full file to memory ?

Thank you,
Nick

**Comment by npatel22526** [comment]
OK I read this issue #61 which answered most of my questions. 
Still curious if filtering for coverage before loading files into methRead would have any adverse impact ?

**Comment by alexg9010** [comment]
Hi Nick,

If you have constraints on memory usage I definitely suggest using tabix
based objects plus applying all of your three suggestions.

1. Split files into CpG, CHH and CHH and process them individually

As you already noticed, the context argument is just for bookmarking,
unfortunately we are not filtering the data based on it. So you have to
create context specific files and process them separately. You can also
pass gzipped files to the methRead function.

2. Split files per chromosome

Splitting and processing files per chromosome is a methods often used by my
colleague to process her data on a shared cluster system with strict
resource management. If you are planning to include all 12 samples in your
analysis splitting by chromosome is highly advised.

3. Filter for coverage before loading the files , this is I am most
interested if it is possible at all.

You could filter the files externally using awk and then process the
prefiltered files. This should reduce the memory footprint when using
methRead, as the files are fully read into memory to generate the tabix
files.

If you are using tabix objects and the analysis steps are using too much
memory you could try to reduce the chunk.size parameter to lower the number
of bases that are processed per chunk.

I hope this helps to keep your memory footprint as low as possible.

Best,
Alex


Sent from mobile.

Nihir <notifications@github.com> schrieb am Fr., 10. Apr. 2020, 18:14:

**Comment by npatel22526** [comment]
Thank you very much for your prompt and detail explanation.
