### ISSUE TITLE
Imputation before running calculateDiffMeth()

### ISSUE THREAD

**Issue by lz870718** [al2na/methylKit#194]
Hi, I've constructed a methylbaseDB with certain cytosine site having missing values in a subset of the sample. 

Then I got below error:
Error in if (any(y < 0 | y > 1)) stop("y values must be 0 <= y <= 1") : 
  missing value where TRUE/FALSE needed

Is there a way to get around it by imputating the methylbaseDB object. Your help is greatly appreciated.

**Comment by alexg9010** [comment]
HI @lz870718,

Right now we don't have any methods for imputation implemented and AFAIK there are no plans to add some. 

If you are dealing with methylation arrays I recommend using a better suited package from bioconductor (https://bioconductor.org/packages/release/BiocViews.html#___MethylationArray).

Should you be dealing with WGBS data, I have some questions:

1. How did you construct the methylBaseDB object and what caused the error? 
Please provide a small reproducible example with a subset of your data. 

2. Why do you want to include these sites with missing values? If you are planning on doing differential analysis, you should not be rely on them. 

Best,
Alex

**Comment by lz870718** [comment]
Hi Alex,
The question applies to a set of hundreds of samples. 
I am afraid if I don't impute/include them I will lose a lot of sites, thus meaningful information.

**Comment by alexg9010** [comment]
Hi @lz870718,


You could reduce the minimum coverage threshold when using methRead, as by
default we are removing sites with less than 10 reads coverage.

Or you could switch to tiling window based analysis, please check the
manual for how to do it.

Best,
Alex

Sent from mobile.

lz870718 <notifications@github.com> schrieb am Do., 30. Apr. 2020, 15:39:
