### ISSUE TITLE
regionCount function does not keep the input region order

### ISSUE THREAD

**Issue by alexyfyf** [al2na/methylKit#199]
Hi,

I found the regionCounts funtion did not return the original order of input regions.

I found the problem likely arises when using Ensembl seqnames (i.e. 1,2,3,...10,11,...)
If the input region is ordered by seqname as 1,10,11,12...,2,20,21,... (which is the default order if I generate DMCs using methylkit pipeline), the output will be coerced into the order of 1,2,3,...10,11,...,20,21.

So I assume this might not be a bug, but should at least highlight the user about this. But I would still hope you can fix this.

Here's a minimal example.
```
dmr[c(1,50,350)]
```
output is 
```
GRanges object with 3 ranges and 5 metadata columns:
      seqnames            ranges strand |    mean.meth.diff  num.CpGs  num.DMCs           DMR.pvalue
         <Rle>         <IRanges>  <Rle> |         <numeric> <integer> <integer>            <numeric>
  [1]        1     971657-971732      * |  22.7421014027064        10         4 4.56421697401645e-05
  [2]       10     264973-265092      * | -38.4704275390885         4         4 6.1342183874346e-149
  [3]        2 83246087-83246137      * |  -33.505645629613         5         4 8.73796847510859e-23
                 DMR.qvalue
                  <numeric>
  [1]  0.000109172802629039
  [2] 1.48908151354975e-145
  [3]  4.15910166143649e-21
  -------
  seqinfo: 22 sequences from an unspecified genome; no seqlengths
```

Then regionCounts
```
rc=regionCounts(cov,dmr[c(1,50,350)])
rc[[1]]
```
The output is 
```
methylRaw object with 3 rows
--------------
  chr    start      end strand coverage numCs numTs
1   1   971657   971732      *      702   356   346
2   2 83246087 83246137      *      590   258   332
3  10   264973   265092      *     2382  1610   772
--------------
sample.id: AY13 
assembly: unknown 
context: CpG 
resolution: region 
```

You can clearly spot that the order changes.
Thank you so much.

**Comment by alexg9010** [comment]
HI @alexyfyf ,

The given regions (Granges/GrangesList object) will be orderd based on
chromosome and position before searching for overlaps, so the resulting
methylKit object might have a different ording than expected. We are doing
this is to ensure that resulting output is consistent for in-memory and
database based objects, as database based objects always have to be sorted to
enable tabix indexing and providing fast random access.

If you to still want get a custom ordering of the output regions you can
order the single regions in any object by providing your indices to the
`select` or `extract` functions.

In your case you would want to do something like this:

```{r}
## sort dmrs first by position
dmrSub <- sortSeqLevels(dmr[c(1,50,350)]) 
dmrSub <- sort(dmrSub[c(1,50,350)]) 
## count over regions
rc=regionCounts(cov,dmrSub)
## reorder by q.value
rc[order(dmrSub$DMR.qvalue, decreasing = FALSE)]
```

**Comment by alexyfyf** [comment]
Thanks!
