### ISSUE TITLE
calculateDiffMethDSS with groups having only 1 sample

### ISSUE THREAD

**Issue by wac** [al2na/methylKit#204]
Currently when attempting to use calculateDiffMethDSS with groups of only 1 sample it appears to run but eventually crashes with:

Using internal DSS code...
Error in rowMeans(p) : 'x' must be an array of at least two dimensions

This can be tested using the internal data with
```
meth.test=reorganize(methylBase.obj, sample.ids=c("test1", "ctrl1"), treatment=c(1,0))
calculateDiffMethDSS(meth.test)

```
The DSS documentation appears to indicate that it should work without replicates (like the Fisher test) but either way the error is unclear and appears to be caused by the number of samples in the groups.

Thank you!

**Comment by al2na** [comment]
It doesn't work with single sample per group afaik. Also, it doesn't
indicate that in our documentation.
You can try to original DSS package, maybe that works with single sample
per group.
