### ISSUE TITLE
Annotation Files 

### ISSUE THREAD

**Issue by sridewi1** [al2na/methylKit#207]
Hi,

I am facing a problem with the CpG annotation file. I followed the instructions on how to download the annotation file from but after reading it into R using
 `cpg.obj=readFeatureFlank("/media/Berechnungen/Referenzgenom/mm10/Annotations/mm10.refseq.CpG.bed",feature.flank.name=c("CpGi","shores"))` 
there was no object could found on the list. I really appreciate any kind of help. 

![grafik](https://user-images.githubusercontent.com/24940249/85694455-6bbd1880-b6d7-11ea-8533-2549f886714a.png)

thanks,
Dewi

**Comment by alexg9010** [comment]
Hi @sridewi1,

Could you please give us more information about the error. I do not see any error message in your screenshot. 
Also please post the commands that lead to your error. 

Best,
Alex

**Comment by sridewi1** [comment]
Hi @alexg9010 ,

thank you for the reply. First I followed the "Downloading Annotation Files" steps as suggested. 

> From here on you can either download gene annotation or CpG island annotation.
> 1. For gene annotation, select "Genes and Gene prediction tracks" from the "group" drop-down menu. Following that, select "Refseq Genes" from the "track" drop-down menu. Select "BED- browser extensible data" for the "output format". Click "get output" and on the following page click "get BED" without changing any options. save the output as a text file.
> 2. For CpG island annotation, select "Regulation" from the "group" drop-down menu. Following that, select "CpG islands" from the "track" drop-down menu. Select "BED- browser extensible data" for the "output format". Click "get output" and on the following page click "get BED" without changing any options. save the output as a text file.
> 

after I downloaded the data, I wanted to annotate the differentially methylated bases/regions, so I used the `readFeatureFlank()` function to save the annotation information for the CpG island (CpGi and shores) as follow:

` cpg.obj=readFeatureFlank("mm10.refseq.CpG.bed",feature.flank.name=c("CpGi","shores"))`

but unfortunately I could not find any information for CpGi and shores in the `cpg.obj` object, it was just empty. There wasn't any error message shown as well. Therefore I was not able to annotate the differentially methylated bases/regions to CpGi and shores and plot it into the pie chart. 

here is the reference I used [mm10.refseq.CpG.zip](https://github.com/al2na/methylKit/files/5069211/mm10.refseq.CpG.zip)

thanks in advance for your help,
Dewi

**Comment by alexg9010** [comment]
Hi @sridewi1 ,

Unfortunately I cannot reproduce the error with the file that you provided, for me running your code does work without any problems.  One difference that I see however, is that based on the screenshot you provided your `cpg.obj` is a `GenomicRangesList`, while in my case it is a `GrangesList`, indicating recent changes in the GenomicRanges package. 

My suggestion would be to update all your installed packages and make sure you are using the latest versions of GenomicRanges, methylKit and genomation, as the `readFeatureFlank` function is defined in the genomation package. 
This can be done with `BiocManager::install()` for all packages, or if you have devtools installed you could also use `devtools::install_bioc("methylKit",dependencies = TRUE)`.



Best,
Alex

**Comment by sridewi1** [comment]
Hi @alexg9010 

thank you for the answer and it was indeed a problem from the GenomicRanges package. Now that I updated my R version and all the packages, I didn't face any problem with the annotation file anymore. Thank you for your help!

Best, 
Dewi
