### ISSUE TITLE
makeMethylDB overwrites existing DB files

### ISSUE THREAD

**Issue by niahughes** [al2na/methylKit#208]
Is there a way to alter makeMethylDB's output filenames? As it stands, after reading in methylRaw files to memory (in my case, to subset on ranges), writing them back out to flatfiles overwrites the originals. This doesn't appear to be a problem for methylBase in my quick tests.

An example using the included example files:
```
# Read in files as DB objects
file.list=list( system.file("extdata", "test1.myCpG.txt", package = "methylKit"),
               system.file("extdata", "test2.myCpG.txt", package = "methylKit"),
               system.file("extdata", "control1.myCpG.txt", package = "methylKit"),
               system.file("extdata", "control2.myCpG.txt", package = "methylKit") )
myobjDB=methRead(file.list,
                 sample.id=list("test1","test2","ctrl1","ctrl2"),
                 assembly="hg18",
                 treatment=c(1,1,0,0),
                 context="CpG",
                 dbtype = "tabix",
                 dbdir = "methylDB"
)

# Create GRanges to subset
region <- GRanges(seqnames=c("chr21"), 
                      ranges=IRanges(start=c(9764513 ),
                                     end=c(9906616)),
                      strand="*")

myObj.subset=selectByOverlap(myobjDB, region) # subset files, reading them into memory
myObjDB.subset=makeMethylDB(myObj.subset, "methylDB") # return files to DB objects
```
```
> getDBPath(myobjDB)
[1] "C:\\Users\\Nia\\Documents\\methylDB/test1.txt.bgz" "C:\\Users\\Nia\\Documents\\methylDB/test2.txt.bgz" "C:\\Users\\Nia\\Documents\\methylDB/ctrl1.txt.bgz"
[4] "C:\\Users\\Nia\\Documents\\methylDB/ctrl2.txt.bgz"

```
```
> getDBPath(myObjDB.subset)
[1] "methylDB/test1.txt.bgz" "methylDB/test2.txt.bgz" "methylDB/ctrl1.txt.bgz" "methylDB/ctrl2.txt.bgz"
```

**Comment by alexg9010** [comment]
Hi @niahughes,

By design the tabix files for the very initial methylRawDB objects are named after their sample ids and we do not check for filename clashes with them, as they usually stay unaltered.  However there are two ways to mitigate your problem:
You could either change your subsetted sample ids with `getSampleID(x) <- c(newNames)`, or my suggestion would be to change the `dbdir` when calling `makeMethylDB`. 

Best,
Alex

**Comment by niahughes** [comment]
Thanks Alex - changing the `dbdir` is a good workaround. For what it's worth, the files I subset weren't the very first methylRaw files (they had been filtered and tiled) but I don't think that matters.
