### ISSUE TITLE
Issue with methRead to make DB: tabix files seem empty

### ISSUE THREAD

**Issue by sformic** [al2na/methylKit#209]
Good evening, I have an issue I cannot solve when using methRead to store files as tabix. The object seems to be made:

```
mrlDB

methylRawListDB object with 12 methylRawDB objects

methylRawDB object with 26797423 rows
--------------
--------------
sample.id: D0-1 
assembly: mm10 
context: CpG 
resolution: base 
dbtype: tabix 

methylRawDB object with 28788291 rows
--------------
--------------
sample.id: D0-2 
assembly: mm10 
context: CpG 
resolution: base 
dbtype: tabix
```

However, when I run the command 
```mrlDB_tiles_200 <- regionCounts(object = mrlDB, regions = tiles_200, chunk.size = 1e6, cov.bases = 20, save.db = TRUE, suffix = "tiles_200", dbdir = "methylDB")```

I get this error:

checking wether tabix file already exists:
methylDB/D0-1_tiles_200.txt.bgz
tabix file is new.
continuing now ...

compressing the file with bgzip...
making tabix index...
Error in getTabixByChunk(tbxFile, chunk.size = nrow, return.type) : 
  the tabix file seems to be empty. stopping here.

Ps: I see the tabix files in the methylDB folder and they are 1.5 Mb in size, I do not know whether this is an expected size.

Thank you!

@katwre

**Comment by katwre** [comment]
this issue was solved with Sara via skype call. @sformic , whenever you have more issues, feel free to just open a new issue here on github 
Cheers,
Kasia
