### ISSUE TITLE
confusion about when p-value adjustment occurs

### ISSUE THREAD

**Issue by r-mashoodh** [al2na/methylKit#212]
Hello, sorry for the potential confusion on my part but I'm curious where p-value adjustment is occuring in the process of calculating differential methylation.

For example, if I do the following:
```
diff.meth <- calculateDiffMeth(Gene.Counts, mc.cores=1, adjust="none")

tmp <- getData(diff.meth) %>% 
  filter(pvalue < 0.05)

length(which(tmp$pvalue < 0.05))
# [1] 426
```
That suggests there are 426 sig methylated regions (without p-value correction)

Now if I do the following:

```
sig.genes <-getMethylDiff(diff.meth, difference=0) 
sig.table <- getData(sig.genes)
nrow(sig.table)
#[1] 308
```

Shouldn't it be 426?

**Comment by r-mashoodh** [comment]
Here is leaving adjust as default:

```
diff.meth <- calculateDiffMeth(Gene.Counts, mc.cores=1)

tmp <- getData(diff.meth) %>% 
  filter(pvalue < 0.05)

length(which(tmp$pvalue < 0.05))
# [1] 426
```
now invoking `getMethylDiff`:
```
sig.genes <-getMethylDiff(diff.meth, difference=0, qvalue = 0.01) 
sig.table <- getData(sig.genes)
nrow(sig.table)
[1] 277
```

**Comment by alexg9010** [comment]
Hi @r-mashoodh ,


the `qvalue` corresponds to the `pvalue` if no adjustment is performed, however the default cutoff for `qvalue` is set to `0.01` in `getMethylDiff`, so in your first example you should use 
```
getMethylDiff(diff.meth, difference=0, qvalue = 0.05) 
```
to get the same tables. 

Best,
Alex

**Comment by r-mashoodh** [comment]
Cheers, thanks for the clarification.
