### ISSUE TITLE
How to open files from a external hard drive when using methylkit

### ISSUE THREAD

**Issue by iramai** [al2na/methylKit#213]
Hi! I am new using R packages, and I am having some problems with the first step of methylkit. The bam files I am using are big in size (65GB each one) and I dont have enough space to move them to the computer memory. So I am trying to use your methylkit script with my data files from the external  hard drive.  The thing is that I am not able to do it.  I have been trying and trying and I always received the same error:

"Error in .local(location, sample.id, assembly, save.folder, save.context,  : 
  File supplied as the 'location' argument doesn't exist
can not find file at: "

Instead of "extdata" I am using the location of the data files which is "system.file("D:/4.3.Deduplication/R1C" and the the name of the file. 

I am sure this is a basic R step but I am a lost and would be very grateful if you could help me.

Thanks in advance,

Iraia

**Comment by alexg9010** [comment]
Hi @iramai ,

Thanks for using methylKit! 

Could you please paste here the exact commands you used, otherwise I cannot really tell what you maybe did wrong. 
I can only say that methylKit is complaining about the path you gave, as this does not point to an existing file. 

You can easily verify that the file location truly exist, by running `file.exists(<filepath>)` .

Best, Alex

**Comment by iramai** [comment]
Thanks Alex for answering that fast!
The command that I use is this one

> file.list <- list(system.file("D:/4.3.Deduplication/R1C", "R1C_1_val_1_bismark_bt2_pe.deduplicated.bam", package="methylKit"), system.file("D:/4.3.Deduplication/R1T", "R1T_1_val_1_bismark_bt2_pe.deduplicated.bam", package="methylKit"), system.file("D:/4.3.Deduplication/R2C", "R2C_1_val_1_bismark_bt2_pe.deduplicated.bam", package="methylKit"), system.file("D:/4.3.Deduplication/R2T", "R2T_1_val_1_bismark_bt2_pe.deduplicated.bam", package="methylKit"))
> my.methRaw=processBismarkAln(file.list, sample.id=list("C1", "M2", "C2", "M2"), assembly="mm10", treatment=c(0,1,0,1), read.context="CpG")

If I verify the location it exists:
> file.exists("D:/4.3.Deduplication/R1C/R1C_1_val_1_bismark_bt2_pe.deduplicated.bam")
[1] TRUE

Maybe now you can find the mistake :)
Thanks in advance,

Iraia

**Comment by alexg9010** [comment]
Hi Iraia,

the problem is that you used the `system.file(... , package="methylKit")` command, which is meant to access files that are packaged with methylKit. Please simply omit this and just use the paths to your file when creating the `file.list`, this should fix your problem. 

Best,
Alex

**Comment by iramai** [comment]
OMG!!!! Thank you very much, you are right and I have proved that it works. 
Is it posible to save the "my.methRaw" data in a txt file or something, and in that way avoid to be uploading the files all the time?
Thank you very very much!!

Iraia

**Comment by alexg9010** [comment]
You are welcome :) 

For saving objects Please have a look at the [vignette](https://bioconductor.org/packages/release/bioc/vignettes/methylKit/inst/doc/methylKit.html#1_Introduction), especially the sections about tabix based objects, which can be used as a drop-in replacement for the normal methylKit objects: 
- https://bioconductor.org/packages/release/bioc/vignettes/methylKit/inst/doc/methylKit.html#23_Reading_the_methylation_calls_from_sorted_Bismark_alignments 
- https://bioconductor.org/packages/release/bioc/vignettes/methylKit/inst/doc/methylKit.html#53_Loading_methylDB_objects_from_tabix_files

The tabix files are actually just indexed, bgz compressed tab-separated files, so if you need to you can just uncompress 
 them and treat them as text files.

Best, Alex

**Comment by iramai** [comment]
Hi again Alex!
I have another problem uploading .bam files. I tried your previous recommendations with small size files, but when using 45-50GB .bam datafiles for my.methRaw=processBismarkAln(  R gets stuck. 
Is there another step between bismark and methylkit to convert .bam files in less size datafiles? Or can I use another bismark output file to upload in methylkit using the same protocol as for .bam files?
Thanks in advance,
Iraia

**Comment by alexg9010** [comment]
Hi Iraia,

For processing the bam files directly, you can use another tool called
methylDackel, that can produce methylKit compatible output.
Otherwise you can also use other files produced with  Bismark, like the
Cytosine report or the Cytosine coverage files directly with the methRead
function.

However if memory is the issue, you could split any of the input files
based on chromosome and process each file separately one after another.
This should lower the memory burden.

Best,
Alex

Sent from mobile.

iramai <notifications@github.com> schrieb am Do., 3. Dez. 2020, 17:42:

**Comment by iramai** [comment]
Thanks again! I will try first using citosine report or coverage file which seems easier. Are the results the same using cytosine report or coverage file, instead of sortrd.bam files? Or there is a loss of information in the process?
Thanks in advance
Iraia

**Comment by alexg9010** [comment]
The results should be the same, independently of the input files that you
are providing, if they come from the exact same bismark run. But should you
find differences, please let us know.

Best, Alex

Sent from mobile.

iramai <notifications@github.com> schrieb am Sa., 5. Dez. 2020, 14:52:
