### ISSUE TITLE
Issues creating a methylRawList  from separate methylRaw objects to unite them

### ISSUE THREAD

**Issue by acontrerasg** [al2na/methylKit#217]
Hello,
I have created a bunch of methylRaw objects, 27 of them, different context and treatments.

Now I need to merge the samples I want to compare into a single table with unite.For that, I need to create a methylRawList,  however I cannot find or figure our how to create this list from the methylRaw objects themselves without going back to the original text files. Any suggestion?

 Thanks!

**Comment by alexg9010** [comment]
Hi @acontrerasg,

you may use the methylRawList() constructor function, which takes a treatment vector and corresponding methylRaw objects to combine them into a methlyRawList object. 
But you should not merge objects with different contexts, as detected CpGs won't overlap. 

Best,
Alex

**Comment by acontrerasg** [comment]
Thanks for the quick answer Alex!
Glad to hear it is possible. However,  I cant figure out how to do it. It seems that methylRawList() function is not present in methylkit package (I just reinstall the 1.16 version), maybe I need to call it differently? Could you provide a syntax example? 

Thank you again!
Best,
Adri

**Comment by alexg9010** [comment]
Hi Adri, 
it seems I forgot to export the function, however you should be able to access it with 
```
methylKit:::methylRawList(treatment = c(0,0,1,1), methylRawA1,methylRawA2,methylRawB1,methylRawAB1)
```
or 
```
methylKit:::methylRawList(treatment = c(0,0,1,1), list(methylRawA1,methylRawA2,methylRawB1,methylRawAB1))
```

I'll patch this asap, but I hope this helps for now. 

Best, Alex

**Comment by alexg9010** [comment]
@acontrerasg feel free to reopen, if this is still not working for you.

**Comment by acontrerasg** [comment]
Thanks! It works perfectly now.
