### ISSUE TITLE
Pearson Correlation and Histograms

### ISSUE THREAD

**Issue by Quest96** [al2na/methylKit#218]
Two questions:
So I was making a Pearson Correlation with methylkit and wanted to get the axis to be uniform and all have the same values to compare them more easily. How should I adjust the basic code to get that to happen?
Code I based it off of from the user guide:
meth=unite(myobj, destrand=FALSE)
getCorrelation(meth,plot=TRUE)

Also, can anyone help me understand the Pearson correlation a little more? I understand the bare basics that's being done here. The methylation % is on the x axis. But the histograms in the pearson correlation don't seem to match the individual histograms that I generated using the code in the user guide:
getCoverageStats(myobj[[2]],plot=TRUE,both.strands=FALSE)

Is there something I'm missing? Appreciate.

**Comment by alexg9010** [comment]
Hi @Quest96,

For your first question, I don't see a simple way to achieve this with our exported functions. However, you could take our implementation of the `.plotCorrelation` function (https://github.com/al2na/methylKit/blob/dd8f40c129c95bc4844552e747669a3da8a122ab/R/backbone.R#L1569-L1645)  and try to set both `xlim` and `ylim` in to c(0,1) in the `panel.my.smooth2` function. 

For the second question, as you already noted the correlation figures are based on the percent methylation, so you should compare the histograms to the ones generated by `getMethylationStats` function.

Best,
Alex
