### ISSUE TITLE
possible to let getCorrection to plot multiple group?

### ISSUE THREAD

**Issue by yplee614** [al2na/methylKit#220]
I have 4 group and each have 3 replicates, how can i plot the correction of these samples? Thanks

**Comment by alexg9010** [comment]
Hi @yplee614, 

are you referring to the function `getCorrelation()` and want to calculate the correlation of samples? 
The function `getCorrelation` does not use the information of the treatment value, thus you may just plot the samples all together. 
However, you to see how your samples are clustering based on treatment group, you may use the `clusterSamples()` or `PCASamples()` functions. 

Best, 
Alex
