### ISSUE TITLE
What does assocComp p-values suggest?

### ISSUE THREAD

**Issue by pinki999** [al2na/methylKit#229]
Hi, I am analysing data from two batches and I would like to check if there are batch effects. The assocComp function returns association p-values (eg: 
$batch_id
         PC1          PC2          PC3          PC4          PC5          
0.9635854342  0.0001077354   0.4936436113   0.0244559362   0.1797026503)

I am not sure if there is significant batch effects in this data. How can I decide which component should be used for remove Comp?

Thank you.

Best,
GSK

**Comment by al2na** [comment]
PC2 seems to be associated with the batch, see if removing that helps with
the clustering. You can also use the batch as a covariate during
differential methylation calculation.

Best,
altuna
