### ISSUE TITLE
feature request: tmpdir option for readBismarkCytosineReport function

### ISSUE THREAD

**Issue by avilella** [al2na/methylKit#23]
Would it be possible to explicitly set up the tempdir that is used for reading in the input files for readBismarkCytosineReport? In platforms where the instance has a small /tmp disk space, reading in a bunch of samples may make it run out of space unless tmpdir is set to another mounted point with more space...

Thx

**Comment by avilella** [comment]
An example where it failes to load the last file because of lack of space in the /tmp/ folder:

```
Read 61828164 rows and 7 (of 7) columns from 1.633 GB file in 00:00:36
Read 61828164 rows and 7 (of 7) columns from 1.632 GB file in 00:00:30
Read 61828164 rows and 7 (of 7) columns from 1.632 GB file in 00:00:33
Read 61828164 rows and 7 (of 7) columns from 1.632 GB file in 00:00:33
Read 61828164 rows and 7 (of 7) columns from 1.632 GB file in 00:00:31
Read 61828164 rows and 7 (of 7) columns from 1.633 GB file in 00:00:33
Read 5770521 rows and 7 (of 7) columns from 0.147 GB file in 00:00:03
Error in fread(filepath, ...) :
  File is empty: /tmp/RtmpvDwDzM/TST40-9-4d_S1_L001_R1_001.cutB.sorted.mrgd.dedupled.CpG_report.txt
  Calls: readBismarkCytosineReport -> fread.gzipped -> fread
  In addition: There were 50 or more warnings (use warnings() to see the first 50)
  Execution halted
```

**Comment by avilella** [comment]
The readBismarkCytosineReport /tmp issue may arise again when we run 300 samples of 30x WGBS bismark Cytosine Reports through MethylKit. Is there a way to resolve this issue short term?

**Comment by al2na** [comment]
can you try the new version of the function
https://gist.github.com/al2na/4839e615e2401d73fe51

**Comment by avilella** [comment]
I tried the newest version on the app I am building in Dnanexus, and it very quickly runs out of space or memory (not sure how R handles this):

```
Attaching package: ‘R.utils’
The following object is masked from ‘package:utils’:
    timestamp
The following objects are masked from ‘package:base’:
    cat, commandArgs, getOption, inherits, isOpen, parse, warnings
Loading required package: data.table

Read 0.0% of 61828164 rows
Read 5.2% of 61828164 rows
Read 10.2% of 61828164 rows
Read 14.9% of 61828164 rows
Read 19.7% of 61828164 rows
Read 24.2% of 61828164 rows
Read 27.9% of 61828164 rows
Read 32.4% of 61828164 rows
Read 37.2% of 61828164 rows
Read 41.7% of 61828164 rows
Read 46.2% of 61828164 rows
Read 50.8% of 61828164 rows
Read 55.4% of 61828164 rows
Read 60.3% of 61828164 rows
Read 65.0% of 61828164 rows
Read 69.9% of 61828164 rows
Read 74.0% of 61828164 rows
Read 78.7% of 61828164 rows
Read 83.0% of 61828164 rows
Read 87.5% of 61828164 rows
Read 91.9% of 61828164 rows
Read 97.1% of 61828164 rows
Read 61828164 rows and 7 (of 7) columns from 1.632 GB file in 00:00:29
Error: cannot allocate vector of size 471.7 Mb
Execution halted
Warning message:
system call failed: Cannot allocate memory 
```

Any ideas?

**Comment by al2na** [comment]
It could be related to the machine memory, can you run it on a machine
where you know the config, 61M rows could be to large to handle for that
machine. You can try to preprocess rows that has low coverage via awk or
ses first

On Tuesday, 29 March 2016, Albert Vilella <notifications@github.com> wrote:

> I tried the newest version on the app I am building in Dnanexus, and it
> very quickly runs out of space or memory (not sure how R handles this):
>
> Attaching package: ‘R.utils’
> The following object is masked from ‘package:utils’:
>     timestamp
> The following objects are masked from ‘package:base’:
>     cat, commandArgs, getOption, inherits, isOpen, parse, warnings
> Loading required package: data.table
>
> Read 0.0% of 61828164 rows
> Read 5.2% of 61828164 rows
> Read 10.2% of 61828164 rows
> Read 14.9% of 61828164 rows
> Read 19.7% of 61828164 rows
> Read 24.2% of 61828164 rows
> Read 27.9% of 61828164 rows
> Read 32.4% of 61828164 rows
> Read 37.2% of 61828164 rows
> Read 41.7% of 61828164 rows
> Read 46.2% of 61828164 rows
> Read 50.8% of 61828164 rows
> Read 55.4% of 61828164 rows
> Read 60.3% of 61828164 rows
> Read 65.0% of 61828164 rows
> Read 69.9% of 61828164 rows
> Read 74.0% of 61828164 rows
> Read 78.7% of 61828164 rows
> Read 83.0% of 61828164 rows
> Read 87.5% of 61828164 rows
> Read 91.9% of 61828164 rows
> Read 97.1% of 61828164 rows
> Read 61828164 rows and 7 (of 7) columns from 1.632 GB file in 00:00:29
> Error: cannot allocate vector of size 471.7 Mb
> Execution halted
> Warning message:
> system call failed: Cannot allocate memory
>
> Any ideas?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/al2na/methylKit/issues/23#issuecomment-202795406>
>


-- 
Sent from mobile, excuse the brevity

**Comment by al2na** [comment]
I'm not sure this is still an issue, most likely what I suggested should help.
