### ISSUE TITLE
Using ONT Megalodon bedmethyl files with methylkit

### ISSUE THREAD

**Issue by fidibidi** [al2na/methylKit#231]
Hello all!

After reviewing the contents of methylkit, I was hoping somebody out there might have used ONT Megalodon bedmethyl output files with this software, and if so, be able to share their experience?

Would there be any additional steps to importing this file into methylkit? 

The bedmethyl files from Megalodon look like this...

chr20	71034	71035	.	12	+	71034	71035	0,0,0	12	0.0
chr20	71037	71038	.	12	-	71037	71038	0,0,0	12	0.0
chr20	71038	71039	.	12	-	71038	71039	0,0,0	12	0.0
chr20	71039	71040	.	12	+	71039	71040	0,0,0	12	0.0 

Each column represents the following:

1. Reference chromosome or scaffold
2. Start position in chromosome
3. End position in chromosome
4. Name of item
5. Score from 0-1000. Capped number of reads
6. Strandedness, plus (+), minus (-), or unknown (.)
7. Start of where display should be thick (start codon)
8. End of where display should be thick (stop codon)
9. Color value (RGB)
10. Coverage, or number of reads
11. Percentage of reads that show methylation at this position in the genome

I believe this paper used bedmethyl and these types of bedmethyl files together, I guess I'm just a little unsure of how to do so... 
https://www.biorxiv.org/content/10.1101/2021.05.05.442849v1.full

Any thoughts and suggestions would be welcome!!

**Comment by fidibidi** [comment]
From the documentation

`6.0.9 Can use data from other aligners than Bismark in methylKit ?
Yes, you can. methylKit can read any generic methylation percentage/ratio file as long as that text file contains columns for chromosome, start, end, strand, coverage and number of methylated cytosines. However, methylKit can only process SAM files from Bismark. For other aligners, you need to get a text file containing the minimal information described above. Some aligners will come with scripts or built-in tools to provide such files. See http://zvfak.blogspot.com/2012/10/how-to-read-bsmap-methylation-ratio.html for how to read methylation ratio files from BSMAP (Xi and Li 2009) aligner.`

A reformatting might be in order of my input file?

**Comment by alexg9010** [comment]
Hi @fidibidi,

Thanks for using methylKit!

Based on your input format I think you don't need to do any reformatting,
just make sure you provide the right column number to each pipeline
argument. I would assume in your case the 'fraction' argument should be set
to false, since you have percentage values, but verify this by checking the
methylation stats.

Best,
Alex

Sent from mobile.

fidibidi ***@***.***> schrieb am Mo., 12. Juli 2021, 23:58:

**Comment by alexg9010** [comment]
Hi @fidibidi,

did it work in the end? 
Can we close this issue now?

**Comment by fidibidi** [comment]
Yes! I was able to import my file with this command

`methObj <- methRead(files[[1]], sample.id = "Test 1", assembly = 'hg38', treatment = 0, header=FALSE, context = 'CpG', pipeline = list(fraction = FALSE, chr.col = 1, start.col = 2, end.col = 3, coverage.col = 10, strand.col = 6, freqC.col = 11))`

Currently, I'm trying to figure out how to convert my methylRaw object to a methylBase...

In the methylkit vignette, the command used is:

`meth=unite(myobj, destrand=FALSE)`

However my attempts result in this error. 

`Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘unite’ for signature ‘"methylRaw"’`

**Comment by fidibidi** [comment]
Ah, unite command requires more than one object in the list!
