### ISSUE TITLE
Confusion about the algorithm of calculateDiffMeth when comparing multiple individuals from two groups

### ISSUE THREAD

**Issue by HuangRuocheng** [al2na/methylKit#235]
Sorry to bother you with my broken English and thanks very much for any response!

I am using calculateDiffMeth to compare the methylation between two groups which consist of samples from different individuals, and I set the parameters like:

sample.id = c("Individual1", "individual2", "individual3", "individual4"),  
treatment = c("case", "case", "control", "control")

but I found that in calculateDiffMeth, it will add coverage or numCs from case or control together to calculate meth.diff. I am worried to think Is that valid? Or do I need do some configuration else, as I think it should directly compare numCs/coverage among samples.

**Comment by alexg9010** [comment]
Hi @HuangRuocheng ,

In general the treatment groups have to be integer values, with the lowest number denoting the control and higher numbers denoting treatment groups. This means you should translate your treatment vectore to `treatment = c(1,1,0,0)` for it to work properly. 

It is unfortunate that no error or warning was issue during the creation of your object, so we should try to catch this earlier. 

The introduction of values other than integers for the group labeling is on our [todo list](https://github.com/al2na/methylKit/issues/102), however, it was not too critical so far.

**Comment by HuangRuocheng** [comment]
Thank you very much for your response! I will translate my treatment vector to integers, and it seems I misunderstood the procedure of calculateDiffMeth... Thank you!
