### ISSUE TITLE
methylation direction 

### ISSUE THREAD

**Issue by freedomq8** [al2na/methylKit#237]
Hi there, 

I am trying to figure out the methylation direction i.e hyepr or hypo methylated in my group comparison?

my group comparison as follow controls coded as 0 and cancer patients coded as 1
when I run the differential methylation analysis, I see in the meth.diff column a positive % value which I assume its hyper-methylated and negative % value which I assume its hypo-methylation ?
What I want to know first if my assumption is correct ?
Secondly,  I wanted to know the positive % value mean its hyper methylated in which phenotype group control (0) or cancer patients (1) ?

I am sorry if this is a repeated or trivial question. Just wanted to make sure.

Thanks in advance

**Comment by alexg9010** [comment]
Hi @freedomq8,

With two groups, the function calculateDiffMeth will calculate methylation difference as the difference of treatment (group: 1) - control (group: 0). Thus hyper-methylated (positive values) regions show increased methylation in the treatment group, while hypo-methylated (negative values) regions have reduced methylation in treatment.

I hope this answers your questions. 

Best, 
Alex
