### ISSUE TITLE
Need advice on tiling the genome using computer with limited internal memory

### ISSUE THREAD

**Issue by frylhc** [al2na/methylKit#239]
Dear Altuna and all,
    Got questions again.  I've got 12 samples, 6 for control and 6 for treatment, respectively. When tiling the genome, I set window size as 1000bp and step size as 10bp. Before tiling, the CX reports produced by the Bismark pipeline was read by methRead function and stored as flat file database. The tiling process is memory-consuming, and thus limited internal memory of my computer prevent me from executing DMR analysis. I was wondering if methylKit got solutions to deal with such issues? Thanks.

**Comment by alexg9010** [comment]
Hi frylhc,

I just quickly tested the impact of the step size on the memory footprint and it is having a huge influence on memory consumption. 
My advice would be to increase the step size and have less overlap between the windows, this should lower the memory usage.

Best,
Alex

**Comment by frylhc** [comment]
Hi Alex,

Thanks for you help. I will consider  your advice.

Best,
Ruiying Fu
