### ISSUE TITLE
How to use the function "adjustmethylC" effectively?

### ISSUE THREAD

**Issue by hchetia** [al2na/methylKit#240]
I have Bismark derived coverage files from Whole genome BSseq and oxBSseq . BS has (5mC+5hmC) data while oxBS has (5mC) data only. The vignette for the function "adjustmethylC" asks for a separate 5hmC file. How do I use my available coverage files to derive this 5hmC file and use it for consequent differential analysis using methylkit?

Also, is there any tutorial on using Methylkit for 5hmC analysis from WGBS experiments?

Thanks.

**Comment by alexg9010** [comment]
Hi @hchetia,

I only worked with normal BSseq until now, so I cannot really give you advice on what to expect with oxBS.
However, the `adjustMethylC` function basically corrects the counts of one sample according to another, so I think you could also extract the 5hmC counts based on BS (`mc`-argument) and oxBS (`hmc`-argument) and then proceed with the differential analysis using the new object. 

For more questions regarding 5hmC analysis you may check the methylKit discussion forum, where similar questions were already answered: https://groups.google.com/g/methylkit_discussion/search?q=5hmc

Best, 
Alex

**Comment by hchetia** [comment]
Hi @alexg9010 @al2na 
Thanks for your reply. 
It would be immensely helpful if you would suggest the command to follow to get the 5hmc counts given that I have a 1_BS.cpG.txt and 2_oXBS.cpG.txt inputs.

**Comment by alexg9010** [comment]
HI @hchetia,

I think in this post the commands are well outline: https://groups.google.com/g/methylkit_discussion/c/cMRGGVxRszk/m/_IcfRfVJAgAJ

**Comment by hchetia** [comment]
Got it. Thanks.
