### ISSUE TITLE
hg38 assembly

### ISSUE THREAD

**Issue by hchetia** [al2na/methylKit#241]
How can I use hg38 assembly for creating methylkit object? Does it need any specific format (indexes) of the hg38 or regular fasta?

**Comment by alexg9010** [comment]
Hi @hchetia,

MethylKit itself is assembly-agnostic, the assembly value used by methRead
is just used for book-keeping.

If you want to use another assembly for methylKit you have to do the
bisulfite-aware alignment against this new assembly.

Best,
Alex

Sent from mobile.

hchetia ***@***.***> schrieb am Mo., 8. Nov. 2021, 22:42:
