### ISSUE TITLE
Error with creating methylkit object

### ISSUE THREAD

**Issue by hchetia** [al2na/methylKit#242]
Hi,
I am trying to create a methylkit object using the methread function and CPG counts from Bismark as input. 
Command used-
myobj=methRead(file.list,
+               sample.id=list("1.cpg.txt", "2.cpg.txt", "3.cpg.txt", "4.cpg.txt"),
+                assembly="hg38",treatment=c(1,1,0,0),context="CpG", mincov = 10)

I am getting the foll. error-
`Error in data[, 5] * data[, 6] : non-numeric argument to binary operator`.

Thanks for the help.

Best,
Hasna

**Comment by alexg9010** [comment]
Hi @hchetia,

Could you please also include how the `file.list` object was created. 
Especially, which files are you providing? It seems that the given files do not match the format `methRead` is expecting. 

Best,
Alex

**Comment by hchetia** [comment]
Hi @alexg9010 
I used these cmd to create file list.
`file.list=as.list(list.files(pattern = ".*.txt"))
file.list`

The files I am providing are CpG count files  generated by Bismark using the Bismark methylation extractor function.
Head of a CpG txt file is shown below
![image](https://user-images.githubusercontent.com/64626735/141005466-7cc63e36-cc79-4a8d-92db-edb37c51965c.png)

Best,
Hasna

**Comment by alexg9010** [comment]
Thanks @hchetia,

The file format that you are showing, does not look like the default format. 
You need to change the pipeline argument of the `methRead` function to match the correct format. 
My advice is to look at the details section to check out the supported formats ;).

Best,
Alex
