### ISSUE TITLE
What does this error imply?

### ISSUE THREAD

**Issue by hchetia** [al2na/methylKit#243]
Hi
I used the same reference genome (GRCH38 primary) for bismark alignment with my BS and OXBS runs. So, what does this error imply and how should I resolve this?

`> diffCpGann=annotateWithFeatureFlank(as(myDiff25p,"GRanges"),
+                                     cpg.obj$CpGi,cpg.obj$shores,
+                                     feature.name="CpGi",flank.name="shores")
Warning messages:
1: In .Seqinfo.mergexy(x, y) :
  Each of the 2 combined objects has sequence levels not in the other:
  - in 'x': GL000195.1, GL000224.1, GL000225.1, KI270733.1, KI270754.1, chr1, chr2, chr4, chr8
  - in 'y': chr20, chr21_random, chr22_random
  Make sure to always combine/compare objects based on the same reference
  genome (use suppressWarnings() to suppress this warning).
2: In .Seqinfo.mergexy(x, y) :
  Each of the 2 combined objects has sequence levels not in the other:
  - in 'x': GL000195.1, GL000224.1, GL000225.1, KI270733.1, KI270754.1, chr1, chr2, chr4, chr8
  - in 'y': chr20, chr21_random, chr22_random
  Make sure to always combine/compare objects based on the same reference
  genome (use suppressWarnings() to suppress this warning).
3: In .Seqinfo.mergexy(x, y) :
  Each of the 2 combined objects has sequence levels not in the other:
  - in 'x': chr20, chr21_random, chr22_random
  - in 'y': GL000195.1, GL000224.1, GL000225.1, KI270733.1, KI270754.1, chr1, chr2, chr4, chr8
  Make sure to always combine/compare objects based on the same reference
  genome (use suppressWarnings() to suppress this warning).
4: In .Seqinfo.mergexy(x, y) :
  Each of the 2 combined objects has sequence levels not in the other:
  - in 'x': chr20, chr21_random, chr22_random
  - in 'y': GL000195.1, GL000224.1, GL000225.1, KI270733.1, KI270754.1, chr1, chr2, chr4, chr8
  Make sure to always combine/compare objects based on the same reference
  genome (use suppressWarnings() to suppress this warning).`

**Comment by alexg9010** [comment]
Hi @hchetia,

This warning is informing you that there are chromosomes which are not shared among the objects that you are giving to the function. Usually these are additional contigs in the genome assembly like your "GL000195.1, GL000224.1, GL000225.1 …” sequences, which can safely be ignored if there is no special interest in them. 

The function will return an object that only includes chromosomes that are common, so just make sure that in the resulting object all the chromosomes you expect to be there are included. You might want to check why some of the major chromosomes ("chr1, chr2, chr4, chr8, chr20") are not in common. 

Best,
Alex

**Comment by hchetia** [comment]
Gracias @alexg9010
