### ISSUE TITLE
When to use overdispersion adjustment for calculateDiffMeth

### ISSUE THREAD

**Issue by kellyliyichen** [al2na/methylKit#248]
Hi,

I am running calculateDiffMeth() to calculate the differentially methylated CpG sites of the WGBS dataset. I realize that it has a parameter for overdispersion. When I did not set this parameter, I got some significant CpG sites (some of them even have p-values of 10^-300) and some of them are clustered in certain chromosomes, which seems good. Then I tried setting overdispersion="MN" as suggested, I got less significant CpG sites (which is expected) but they are isolated in different chromosomes. 

My question is how to tell whether I need to set the overdispersion parameter or not? Can I trust the results with or without adjusting the overdispersion? I have read the related code and materials to try to understand the statistical logic behind it. But it seems I still could not have a clear answer. Is there anyone who could help to figure it out? Many thanks for any help in advance!

**Comment by alexg9010** [comment]
Hi @kellyliyichen, 

I am by no means an expert, nor can I explain the statistical logic behind overdispersion correction. 
I can suggest reading the chapter about "Differential methylation detection methods" in our paper (https://www.sciencedirect.com/science/article/pii/S0168165617315936#sec0020) where we evaluated the effect of using overdispersion correction together with different effect size cutoffs. You may find some insights there. 

In general, I would always suggest trying both options and deciding based on the outcome. In the exploratory stage, you may decide to continue with many _possibly significant_ candidate sites and then narrow them down later on. However, it usually depends on the research question at hand, whether you want to continue with many or few candidates. 

As for understanding the logic and decision process, I wonder whether @al2na has some recommendations. 

Best
Alex
