### ISSUE TITLE
How to obtained control and treatment %values instead of the diffmeth % value

### ISSUE THREAD

**Issue by iramai** [al2na/methylKit#249]
Hi!
I have some doubts when visualizing the obtained results. I am interested in producing a file with raw % values of each sample, as a previous outcome of the diffmeth option (where the methylation difference %value is produced). I thought I could obtained this values from the methylbase outcome with the coverage values but I do not find the way to convert that coverage values for each sample to methylation % values. 
I do not know if I'm explaining myself well but I will appreciate some kind of feedback in this issue.
Thanks in advance,
Iraia

**Comment by alexg9010** [comment]
Hi @iramai ,

you may check out the `percMethylation()` function, which gets the percent methylation scores from a methylBase or methylBaseDB object and returns a matrix with percent methylation values per base/region across all samples.

Best
Alex

**Comment by iramai** [comment]
Thank you very much for the aclaration.
It works in the same way for the scores from tiled methylBase?
Thanks again

**Comment by alexg9010** [comment]
Hi @iramai,  yes it should summarize the regions that you provide, independent of being base/region/tile.

**Comment by iramai** [comment]
Ok! Thank!!! I will try both options!
