### ISSUE TITLE
calculateDiffMeth

### ISSUE THREAD

**Issue by DLGisch** [al2na/methylKit#252]
Hello,
I am trying understand the output values in calculateDiffMeth.
I have  this methylbase call by_region
```
 chr     start       end strand coverage1 numCs1 numTs1 coverage2 numCs2 numTs2
1 chr7 131503950 131504508      -        40     22     18        52     36     16
2 chr7 131504509 131505867      -        72     45     27        75     56     19
3 chr7 131506106 131507105      -       191    115     76        78     67     11
--------------
sample.ids: G1  T1
destranded FALSE 
assembly: hg38 
context: CpG 
treament: 1 0 
resolution: region 
```
I do this function call
`calculateDiffMeth(by_region) `

and my result is 

```
------------
   chr     start       end strand       pvalue       qvalue meth.diff
1 chr7 131503950 131504508      - 1.939971e-01 6.531889e-03 -14.23077
2 chr7 131504509 131505867      - 1.542883e-01 6.531889e-03 -12.16667
3 chr7 131506106 131507105      - 2.717544e-05 2.744994e-06 -25.68801
--------------
sample.ids: G1 T1 
destranded FALSE 
assembly: hg38 
context: CpG 
treament: 1 0 
```
The methylkit code do this:

``` 
    set1 is the high, set2 is the low level of the group 
    set1.Cs=Ccols[treatment==levels(as.factor(treatment))[2]]
    set2.Cs=Ccols[treatment==levels(as.factor(treatment))[1]]
    
     #calculate mean methylation change
    mom.meth1    = 100*(subst[,set1.Cs]/subst[,set1.Cs-1]) # get % methylation
    mom.meth2    = 100*(subst[,set2.Cs]/subst[,set2.Cs-1])
     #get difference between percent methylations
    mom.mean.diff=mom.meth1-mom.meth2 
```

I tried to reproduce the result, but probably a didn't take the correctly values.
100*((36/52)/((36/52)-1)) - 100*((22/40)/((22/40)-1)) 
Could you please tell me how this part of the code works? 

Thank you!

**Comment by alexg9010** [comment]
Hi @DLGisch,

when you checked the code, you missed that `Ccols` refers to the column indices of the cytosine columns within the dataframe:

https://github.com/al2na/methylKit/blob/ab60a62e0bd610718fcbb76e9505957c8c3ec15f/R/diffMeth.R#L550-L552

`set1.Cs` and `set2.Cs` are also column indices and point to column 6 (`numCs1`) and 9 (`numCs2`) of the methylBase object, respectively. Thus if you do the calculations of methylation percentage with the corresponding column vectors you should get the correct results. 

Just as a side note, if you want to play with your data using the code from the repo, you may use the `getData()` function to get the data part of your objects. 

Best, 
Alex

**Comment by DLGisch** [comment]
Hi,
 I will check this part. 
Thank you for your attention,
Debora
