### ISSUE TITLE
More DMGs than DMRs

### ISSUE THREAD

**Issue by TSolDour** [al2na/methylKit#253]
Hi, 

I'm working on MethylSeq data in order to compare gene methylation between two treatments using MethylKit. To do so, I want to analyze DMRs based on the results of CpGs differential methylation. But, when I use tileMethylCounts() to create some windows and process calculateMethDiff() function, results are not consistent with DMCs (DMRs are found were there is no DMCs).
A good way to define a DMR would be to consider a DMR when they're at least 2 DMCs in a 1000bp long tile (for exemple). But I can't figure out how to to that into MethylKit environment. 

I hope you'll have any clue to solve this issue.

Thanks, 

Thomas.

**Comment by alexg9010** [comment]
Hi @TSolDour,

Thanks for using methylKit for your research. The function you are looking for is `methSeg()`, which allows you to segment/cluster your DMCs into DMRs based on methylation difference. You may check out [our paper](https://www.sciencedirect.com/science/article/pii/S0168165617315936#sec0040) and [this section of Altuna's book](https://compgenomr.github.io/book/extracting-interesting-regions-differential-methylation-and-segmentation.html#methylation-segmentation) for some explanation and usage examples.
