### ISSUE TITLE
Generating 5mCG per gene  from BS/OXBS data

### ISSUE THREAD

**Issue by hchetia** [al2na/methylKit#254]
Hi @al2na @alexg9010 
I use the methread function to read the coverage files from Bismark.
``
BS_21=methRead("2368_bismark_bt2_pe.deduplicated.bismark.cov.gz",
                 sample.id="2368_BS",assembly="mm10",
                 header=F,skip=0,sep="\t",context="CpG", 
                 pipeline="bismarkCoverage", mincov = 5)
``
However, the resulting methylkit object seems to lose the methylation percentage values generated by Bismark. 

Bismark:
<img width="323" alt="image" src="https://user-images.githubusercontent.com/64626735/161638426-bda3dd3c-4c06-4541-8797-74c7cd73e96f.png">

MethyKitObject:
<img width="519" alt="image" src="https://user-images.githubusercontent.com/64626735/161638488-5652f1a1-92ee-4716-87c6-f103e093c960.png">

Is there a way to retain or read the corresponding percentage methylation values in the foll. scenarios-
1. A single corresponding cov.gz input file? 
2. From methylkit object derived using ADJUSTED methylC outputs?

**Comment by hchetia** [comment]
@al2na @alexg9010 
I was able to retrieve the percentage methylation for the 5mC samples doing some data wrangling.

But for 5hmCs, I am using two samples. The methylkit object after using AdjustMethylC also lacks the percentage methylation values from Bismark. Would adding the corresponding columns from the original coverage file; followed by the subtraction of percent.meth per CpG (derived from Bismark) (BS minus OXBS) be the ideal way to go?
Please advise.

**Comment by alexg9010** [comment]
Hi @hchetia,

We don't have a function to calculate the percent methylation for methylRaw objects. However, you may get these values for each CpG of a single methylRaw sample (retrieved after `methRead` or `adjustMethylC`) by converting the object to a data.frame using `getData` and then simply calculating the fraction of methylation by dividing the numCs column by the coverage column. 

Best,
Alex

**Comment by hchetia** [comment]
Thanks.
