### ISSUE TITLE
Clarifications on filterByCoverage

### ISSUE THREAD

**Issue by franrodalg** [al2na/methylKit#257]
Hi everyone,

I've been playing around with methylKit for the first time recently, and I must admit I'm struggling a bit trying to understand how `filterByCoverage()` works, at least when using a percentile threshold for the upper limit. 

Let's say I request sites above the 90th percentile to be filtered out. 

* Does that mean the 90th percentile _per sample_ or _overall_ on the dataset? (I don't think that's mentioned on the documentation, but I might have missed it). 
* Would a site above such a threshold in a particular sample be removed only in that sample or across the dataset?
* Would we expect sites to experience "partial" filtering? (i.e., the coverage is reduced, but not completely gone)

Asking because we observe the following in our data (showing two samples out of many for the sake of simplicity):

![image](https://user-images.githubusercontent.com/7487122/170533615-b51f1d39-90fd-428a-9d2e-f2319ee83843.png)

* There are some sites on which the coverage remains unaltered (straight diagonal line)
* Other sites are completely gone after filtering (horizontal line on the x axis). I would have expected, however, that only high coverage sites would be affected in this way, but there are clearly points with relatively low coverage that have been brought to 0 after filtering.
* Finally, there are intermediate points, where coverage is reduced, but not brought to 0, with a similar, but not exact, ratio.

I would appreciate if you could help me understand why is this all the case.

It would also be great if you could point me at any resource that could help set a sensible threshold, be absolute or relative.

Cheers,
Fran

**Comment by franrodalg** [comment]
HI @alexg9010,

Thanks for your answers.

I am trying to figure out if the destranding has an impact on the partially-filtered positions, but that part makes sense.

Regarding the low coverage issue, my call is:

```
methylKit::filterByCoverage(methRaw, hi.perc = 90)
```
so I'm not explicitly requesting any low-end threshold. As far as I understand it, the default value for both `lo.count` and `lo.perc` is `NULL`, right? So there shouldn't be any filtering unless explicitly requested. On top of that, there are clearly positions with the same coverage that are left untouched. 

Am I missing something?

I will read the book you suggest, in case there are any recommendations about suitable threshold, but if you have any insight in that regard, it would be great.

Cheers,
Fran

**Comment by franrodalg** [comment]
Hi @alexg9010, did you have the chance to think about what the above could be happening?

Cheers,
Fran

**Comment by alexg9010** [comment]
Hi @franrodalg,

Sorry for the late reply.  I tried to reproduce what you had seen, but could not observe similar patterns. 

When using the internal sample data, only the data with coverage higher than the given percentile is removed: 
``` r
library(methylKit)
data(methylKit)

# use internal methylRawList.obj
filtered.methylRawList.obj <- filterByCoverage(methylRawList.obj, hi.perc = 90) 

# sample1  coverage before filtering
getCoverageStats(methylRawList.obj[[1]])
#> read coverage statistics per base
#> summary:
#>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#>   10.00   16.00   43.00   62.15   86.00  818.00 
#> percentiles:
#>      0%     10%     20%     30%     40%     50%     60%     70%     80%     90%    95%     99%   99.5%   99.9%    100% 
#>  10.000  12.000  14.000  18.000  27.000  43.000  61.000  79.000  96.400 133.000 158.000 309.000 388.455 522.485 818.000

# sample1 coverage after filtering
getCoverageStats(filtered.methylRawList.obj[[1]])
#> read coverage statistics per base
#> summary:
#>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#>   10.00   15.00   33.00   46.03   72.00  132.00 
#> percentiles:
#>    0%   10%   20%   30%   40%   50%   60%   70%   80%   90%   95%   99% 99.5% 99.9%  100% 
#>  10.0  11.0  14.0  17.0  22.0  33.0  51.0  67.0  81.0  98.0 113.5 126.0 128.0 131.0 132.0

# sample2  coverage before filtering
getCoverageStats(methylRawList.obj[[2]])
#> read coverage statistics per base
#> summary:
#>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#>   10.00   16.00   26.00   34.45   39.00  630.00 
#> percentiles:
#>      0%     10%     20%     30%     40%     50%     60%     70%     80%     90%    95%     99%   99.5%   99.9%    100% 
#>  10.000  11.000  14.000  17.000  20.000  26.000  30.000  36.000  42.000  60.000 78.750 195.800 328.300 441.945 630.000
    
# sample2 coverage after filtering
getCoverageStats(filtered.methylRawList.obj[[2]])
#> read coverage statistics per base
#> summary:
#>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#>   10.00   15.00   23.00   25.51   35.00   59.00 
#> percentiles:
#>     0%    10%    20%    30%    40%    50%    60%    70%    80%    90%    95%   99%  99.5%  99.9%   100% 
#> 10.000 11.000 14.000 16.000 19.000 23.000 28.000 32.000 38.000 43.000 48.000 57.000 57.985 59.000 59.000
```

Also, visual inspection of the coverage values with a histogram shows that regions with coverage below the `hi.perc` percentile are untouched.

```r
covRaw <- lapply(setNames(methylRawList.obj, 
                          getSampleID(methylRawList.obj)),
                 function(methRaw) {
  with(getData(methRaw), 
       setNames(coverage,paste(chr,start,end,strand,sep = ".")) )
} )
covFilt <- lapply(setNames(filtered.methylRawList.obj, 
                           getSampleID(filtered.methylRawList.obj)),
                  function(filtered.methylRaw) {
  with(getData(filtered.methylRaw),
               setNames(coverage,paste(chr,start,end,strand,sep = ".")) )
})

oldpar <- par()
par(mfrow = c(2,2))
mapply(function(covRaw, covFilt) {
  
plot(density(covRaw), col = "grey", main = "Density Plot of Coverage")
lines(density(covFilt), col = "red")
legend("topright",legend = c("Raw", "Filtered"), col = c("grey","red"),lty = 1)

h <- hist(covRaw, col = "grey", breaks = 50, main = "Histogram of Coverage")
hist(covFilt,add =TRUE, col = rgb(1,0,0,0.4), breaks = h$breaks)
legend("topright",legend = c("Raw", "Filtered"), col = c("grey","red"),lty = 1)
},
covRaw = covRaw[1:2], 
covFilt = covFilt[1:2]
)
par(mfrow = c(1,1))
```

![](https://i.imgur.com/2FVepFY.png)

<sup>Created on 2022-06-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

However, given that I don't know exactly how you processed the data in the first place, it would be great if you could post a minimal reproducible code example to show how you produced your figures.  

Best 
Alex

**Comment by franrodalg** [comment]
Thank you, Alex. 

I've been trying to reproduce the issue, and I now I think I'm getting the expected behaviour! I have no idea what could be happening before. Maybe there was a conflict with another package, or something like this, but on a "clean" session, sites seem to be filtered as intended. If I ever see any unexpected behaviour again, I'll make sure to try to narrow down the issue and report it here again, but I think that I can close this at the moment.

Thanks for double-checking anyway!
