### ISSUE TITLE
Function for converting Granges to Methylkit Object

### ISSUE THREAD

**Issue by hchetia** [al2na/methylKit#258]
HI @al2na @alexg9010 
My goal is to remove SNPs  (a GRanges object) from my methylBase object. I was able to achieve this by converting the methylBase object to GR object and then removing the overlaps between both objects using a dplyr function. However, I couldn't find a way to convert the new SNP-free GR object to a methyBase object. Is there any methylkit/genomation function (that I couldn't spot in your manual ) that addresses this issue?
If not, is there a way to use the function "selectByOverlaps" function in a reverse way, i.e., selecting rows in a methylBase object that does not overlap with another GRanges?
Best,
Hasna

**Comment by alexg9010** [comment]
Hi @hchetia,

Usually, we report GRanges object at the end of an analysis; thus, we are not providing a function to convert it back into a methylKit object.  Your idea to use the `selectByOverlaps` function in an "inverse" fashion sounds good and could be implemented in the future, but it is not possible now. 
Instead, to achieve your selection of non-matching rows in a methylKit object, you could subset your object as described in the [vignette](https://bioconductor.org/packages/release/bioc/vignettes/methylKit/inst/doc/methylKit.html#54_Selection:_subsetting_methylKit_Objects). 

```
library(methylKit)
data("methylKit")

# prepare some GRanges object 
gr <- as(methylDiff.obj,"GRanges")
# prepare filter
snps.gr <- gr[abs(gr$meth.diff) > 50]

# keep only rows with no snps
fitered.methylBase.obj <- methylBase.obj[!as(methylBase.obj,"GRanges") %over% snps.gr]
```

**Comment by alexg9010** [comment]
Hi @hchetia,

When using the filtering code exactly as proposed, I gain a `"methylBase"` object which can also be used with the `PCASamples` function. However, your conversions from `"methylBase"` to `"data.frame"` via `"GRanges"`  renders the `comsnpfree.pcaclean` incompatible with methylKit functions which expect methylKit objects. 

Please note the generic function `prcomp` acts on a numeric matrix and does not know how to deal with this methylBase-like data.frame. Usually we would pass it the percent methylation matrix of all samples, which is prepared in the PCASamples function (see [code](https://github.com/al2na/methylKit/blob/9620cd686a14483f2158c75805c952d066c7b7f8/R/clusterSamples.R#L401-L441)) 

Please post the code you used for the filtering and the conversions. Maybe there is some easy fix to your problem. 

Best
Alex

**Comment by alexg9010** [comment]
Hi @hchetia,


Concerning the point 
>  Your example above uses a mathematical function over one column (methdiff) from the original GR

This was just meant to exemplify how to create a filter for subsetting the `methylBase` object. This filter vector could either be a boolean (TRUE/FALSE) vector or a vector of row numbers. Just like you would do with normal data.frames. 

This code should work for your problem: 
```
# convert "methylBase" into GRanges to perform overlap
meth_5hmC_cov5_noXYM.gr <- as(meth_5hmC_cov5_noXYM, "GRanges")
# prepare boolean filter vector to subset the original object
comSNP_overlap <- meth_5hmC_cov5_noXYM.gr %over% comSNP.gr
# omit all rows where overlap with SNP was detected
comsnpfree.meth_5hmC_cov5_noXYM <- meth_5hmC_cov5_noXYM[!comsnpoverlap]

pca_5hmC_nocomSNP <- PCASamples(comsnpfree.meth_5hmC_cov5_noXYM, adj.lim = c(1,1), obj.return = TRUE)
```

Please note that most of the functions methylKit provides will take methylKit-based objects as input. 
If you are not sure what is required, check the respective functions help. Most of the time we tried to be rather specific about the function arguments. 

Best,
Alex

**Comment by hchetia** [comment]
@alexg9010 Your code worked. Thanks for taking time to help me out.
