### ISSUE TITLE
How does calculateDiffMeth cope with multiple treatment groups (>2) ?

### ISSUE THREAD

**Issue by erikras12** [al2na/methylKit#261]
Hello,

I ran calculateDiffMeth with a treatment vector length of 8 and I am unsure how the comparisons are made in this context.
Are all comparisons made or are 7 of the treatments compared to just one etc. ?

**Comment by alexg9010** [comment]
Hi @erikras12,

You are basically running a logistic regression with eight groups. The methylation difference at each given site will correspond to the maximal methylation difference between the groups: 
https://github.com/al2na/methylKit/blob/9620cd686a14483f2158c75805c952d066c7b7f8/R/diffMeth.R#L306-L312

We did not implement a function to run all comparisons, but you may achieve this manually by [reorganizing](https://www.rdocumentation.org/packages/methylKit/versions/0.99.2/topics/reorganize) your objects in a loop. 

Best
Alex
