### ISSUE TITLE
How to merge when reading multiple files using readMethylDB?

### ISSUE THREAD

**Issue by coffeeCowLu** [al2na/methylKit#263]
How to merge when reading multiple files using readMethylDB?

myobj <- lapply(files, function (x){readMethylDB(x)})
meth <- unite(myobj, destrand = FALSE)

Error in (function (classes, fdef, mtable)  :
  unable to find an inherited method for function ‘unite’ for signature ‘"list"’

**Comment by alexg9010** [comment]
Hi,

You have to convert the `list` into the appropriate type using the
`methylRawList` function.

Best,
Alex

Sent from mobile.

coffeeCow ***@***.***> schrieb am So., 21. Aug. 2022, 02:22:
