### ISSUE TITLE
simData for regions

### ISSUE THREAD

**Issue by malonzm1** [al2na/methylKit#264]
Hi!

According to the documentation for simData, "if add.info=TRUE a list containing the methylbase object and the indices of all treated sites (differentially methylated bases or regions)". How do I specify a list for differentially methylated regions?

Thanks and good day.

**Comment by alexg9010** [comment]
Hi @malonzm1,

You can not specify a list for differentially methylated regions, but when you set `add.info=TRUE`, you will retrieve the list of actually treated sites to subset the simulated methylBase object.

Best
Alex

**Comment by malonzm1** [comment]
Hi @alexg9010 ,

Thanks! How do I then subset regions from the simulated methylBase object?

Br,

**Comment by alexg9010** [comment]
Hi @malonzm1,

after simulating the methylBase object, you may subset it using data.frame-like subsetting with `[`. 
Please see this snippet, for how to to this: 

```
library(methylKit)
data(methylKit)

# Simulate data for 4 samples with 20000 sites each.
# The methylation in 10% of the sites are elevated by 25%.
sim.methylBase=dataSim(replicates=4,sites=2000,treatment=c(1,1,0,0),
                      percentage=10,effect=50,add.info = TRUE)

# with add.info=TRUE, the output will be a list with the first element being the
# methylbase object and a vector of indices that indicate which CpGs should be
# differentially methylated.
sites <- sim.methylBase[[2]]
my.methylBase <- sim.methylBase[[1]]

# This vector can be used to subset simulated methylBase or methylDiff object with differentially methylated bases.
my.methylBase.Diff <- my.methylBase[sites,]
my.methylBase.noDiff <- my.methylBase[-sites,]
```

Best
Alex

**Comment by malonzm1** [comment]
Ok. Thanks!
