### ISSUE TITLE
Is this repo still relevant?

### ISSUE THREAD

**Issue by hukai916** [al2na/methylKit#276]
Hi there, 

I would like to fork the most up-to-date `methylKit` branch, is the `master` branch to go for? I noticed that the version on Bioconductor is  already `1.24.0` whereas the lasted tag from this repo is still at `0.99`. Any idea?

--Kai

**Comment by alexg9010** [comment]
Hi @hukai916, 

Yes, the `master` branch would be the one to choose. In terms of commits this is in sync with the version on Bioconductor, except for automated version bump commits. 

We did not set automated releases on github, that's why there we still have the version from 2016.

Best,
Alex
