### ISSUE TITLE
Can I perform differential methylation analyses using quantitative traits instead of binary?

### ISSUE THREAD

**Issue by mariazanti** [al2na/methylKit#277]
Hello. 

I am currently using methylkit to compare differential methylation between groups. 

Can I perform differential methylation analyses using quantitative traits instead of binary? (linear regression instead of logistic)

Thank you in advance for the help.

**Comment by alexg9010** [comment]
Hi @mariazanti,

this is not possible with methylKit. 
For using linear regression models I suggest checking out limma or searching among the methylation-array focused packages within bioconductor, like minfi. 

Best,
Alex
