### ISSUE TITLE
error of calculateDiffMeth function

### ISSUE THREAD

**Issue by pengchy** [al2na/methylKit#28]
Hi,

I am running the latest version of methylkit. However, I always encounter the following error for calculateDiffMeth function. The methrw.ut is produced successfully by unite function.

Best,
Pengcheng Yang

================= the error message: =================
methrw.ut=unite(methrw,destrand=FALSE)
methrw.dmb=calculateDiffMeth(methrw.ut,num.cores=5) 
Error in pi0 * length(order_rawp) * order_rawp : 
  non-numeric argument to binary operator
Calls: calculateDiffMeth ... calculateDiffMeth -> fix.q.values.fisher -> SLIMfunc -> QValuesfun
In addition: Warning message:
In parallel::mclapply(my.f.list, f.fisher, mc.cores = num.cores) :
  all scheduled cores encountered errors in user code

**Comment by al2na** [comment]
please use https://groups.google.com/forum/#!forum/methylkit_discussion and send a reproducible example
