### ISSUE TITLE
Which parameter determined the  p value and q value but doesn't change the meth.diff ?

### ISSUE THREAD

**Issue by DengEr-1993** [al2na/methylKit#285]
Hello @alexg9010 ,

I have a small question about the `calculateDiffMeth()` function.

I can get different results if I  use different parameters in `calculateDiffMeth()` 

but I want to know if any parameters can only change the p value and q value but will not affect the meth.diff result ?

For exmaple, based on the scripts below, respectively :

myDiff_new = calculateDiffMeth(meth_new, overdispersion="MN", test="Chisq", num.cores = 10)
or
myDiff_new = calculateDiffMeth(meth_new, covariates = covariates, overdispersion="MN", test="Chisq", num.cores = 10)

how can I use other different paramters to change p value and q value but will not affect the meth.diff result of each  line ?

I have confirmed  that parameter "test=()"  can change both values.  Can `adjust=() ` does it  ?

Best,
Xiangyi

**Comment by alexg9010** [comment]
Hi @DengEr-1993,

Yes, correct. To modify the outcome of the p-value adjustment (q-value), simply change the `adjust` parameter of the `calculateDiffMeth` function. This should allow you to fine-tune the results and not change the reported methylation difference.

Best,
Alex
