### ISSUE TITLE
Import CpG_context file to Methylkit

### ISSUE THREAD

**Issue by manjumoorthy95** [al2na/methylKit#286]
Hi. I am using Bismark pipeline to process my Whole genome BS data. So after running Bismark methylation extract command I got 3 different text files for each context CpG, Chh and Chg. I know we can import the .cov or bam files to Methylkit. But what I specifically want to understand is that, is there any method where I can import the CpG_Context.txt into the Methylkit? 

Kindly guide.

**Comment by alexg9010** [comment]
HI @manjumoorthy95,

When you say `CpG_Context.txt` are you referring to the file generated with `bismark_methylation_extractor --cytosine_report`? 
If yes, this can be read by using `methRead` with the `pipeline` argument set to "bismarkCytosineReport". 

If this is not how the file was generated, it would be great if you could specify how this file was created. 

Best,
Alex

**Comment by alexg9010** [comment]
I see. No, the default output format generated by the `bismark_methylation_extractor` is not supported by methylKit. These files summarize methylation calls on the read level, but we require per-locus information.

Best,
Alex
