### ISSUE TITLE
Could methylKit be used to compare one group with the other one group which was merged by mulitple groups ?

### ISSUE THREAD

**Issue by DengEr-1993** [al2na/methylKit#289]
Hello there,

A great package which help me solve many problems.

I have a  question just as the title said:

I have several groups , for instance, Group A,  B, C, D, E and so on.

As we all know we can compare two of them: A vs B or  A vs C.  It is ok and it works well.

But if I want to explore the difference between A and the other four groups (B, C, D, E), can I `unite` the rest four groups together as 0 and Group A as 1  to do `calculateDiffMeth` function ?

On the one hand,
I am not sure because the covariance (or specific group characteristic ?) exists between different  groups, so I unite B, C, D, E together here will cause uncertain results.

On the other hand, if I can do this as usual, what extra solution should I take to deal with this influence or I just ignore it  ?

So I hope you could give me some advice on this question.

I would really appreciated it if you can answer question.

Thank you in advance.

Best,
xiangyi

**Comment by alexg9010** [comment]
Yes, just leave the covariate parameter empty.

DengEr-1993 ***@***.***> schrieb am Mo., 26. Juni 2023, 18:02:
