### ISSUE TITLE
`read.bismark` fails on windows

### ISSUE THREAD

**Issue by CathG** [al2na/methylKit#29]
The function `read.bismark` fails to find the perl script `methCall.pl` on windows because of the space in the program folder name ("Program Files").  
To make it work, I modified `read.bismark` function to add quotes around the path name (variable `ex.loc`).

**Comment by al2na** [comment]
@CathG, thanks for the note. Can you you try the development version? @alexg9010 converted the perl scripts to C++ and this is now part of methylKit via Rcpp.

**Comment by CathG** [comment]
@al2na thank you for your reply. The development version indeed solves the issue (it also corrects the nolap/paired typo I also reported), thanks.

**Comment by al2na** [comment]
@CathG, great! could you also let us know how it works for you. We tested it small samples but would be good to know if it works or not for other users as well.
