### ISSUE TITLE
If there is a parameter which can be used to determine how many CpG site (not Coverage on one CpG site) will be tiled together ?

### ISSUE THREAD

**Issue by DengEr-1993** [al2na/methylKit#291]
Hi @alexg9010 ,

I have  a small question.

I did almost the whole DMR calling workflow and it works well.

Here is my partial code:

```
myobj = methRead(file.list,
                     sample.id = as.list(vec_names_selected),
                     assembly  = "hg38",
                     treatment = c(rep(1, vec_n_Group1), rep(0, vec_n_Group2)),
                     context   = "CpG",
                     mincov    = 1
    )

 tiles = tileMethylCounts(myobj,
                               win.size = 500, 
                               step.size = 500, 
                               mc.cores = 30,
                               cov.bases = 5)
      
 filtered_tiles = filterByCoverage(tiles, lo.count = 5)

meth_all_tiles = methylKit::unite(filtered_tiles, mc.cores = 30, min.per.group = 2L)
```

For example,  if I used only 5 in tileMethylCounts() and filterByCoverage(),

what's the different meaning between the two functions ?

If the parameter  in the second  function means  remove CpG site counts lower than 5 ? 

But it may be wrong  according the help in R.

lo.count	
An integer for read counts.Bases/regions having lower coverage than this count is discarded

Here it mostly means lo.count still calculate the Coverage reads.

If so,  there must be difference between the two functions.

So I guess,  in tileMethylCounts(), from CpG to tile,  here I used 500bp,

Does it means in 500bp, all the CpG reads do a sum as the total region reads, or mean reads of all CpG reads in 500bp ?

I am really confused. 

Because if it is right (the last sentence above),

 lo.count in tileMethylCounts()  must be a standard which is used to  remove some tiles which is transfered by CpGs in low quality.

For exmaple , in a specific 500bp region, there are 5 CpG sites, contains 5, 6, 9, 7, 8 reads coveraged, respectively. 

So in this 500bp region , how many CpG Coverage is there ?  sum() 30 reads or  mean()  7 reads ?

I hope you can give me a clear explaination when you are free.

Thank in advance.

**Comment by alexg9010** [comment]
Since you used methRead with min.cov=1 this is will include bases with very low quality/ not reliable methylation calls. If you are dealing with low coverage data ( generate from low-input material) I would suggest to require at least a coverage of 3 reads per base, but in general a higher coverage threshold of 10 reads per base is recommended.

**Comment by DengEr-1993** [comment]
So, 
firstly, input with a coverage of 3 reads per base; 
then, do the  filterbyCoverage, 
and in the end, do tileMethylCounts() ?
Do you have any other suggestions on my parameters except the workflow order and parameters in? Thanks

**Comment by alexg9010** [comment]
Hi @DengEr-1993 


>   `mincov` means  the least coverage reads in every sample is 3 , not in all samples simutaneously, is that right ? 

it is the minimum read coverage to be included in the methylKit objects. Any methylated base/region in the text files below the mincov value will be ignored. this holds true for **every** sample.


> By the way, if I use mincov = 5 here,  or 3 as you said,  then if it is not necessary for me to  do filterByCoverage (myobj, lo.count = 5) then ? 

not necessarily. You might need to include this step when reading tabix files though, since they are not filtered but directly loaded.

>  If I set mincov=5 at the first step, here filterByCoverage(lo.count = 5)  has the same function, right ?

yes. 

> A small question: here I set  win.size = 500, step.size = 500, is that ok? Because I want a 500bp window. But I don’t know the difference between win.size and step.size. 

yes, this should work. `win.size` sets the size of each window, `step.size` sets how far the next window will be shifted relative to previous one. if `step.size` is smaller than `win.size` you will get overlapping tiles . 


> Finally, I understand the cov.bases(), it means the number of CpG sites in a specific window (tile region). So there must be more than 5 CpG sites but not  how many reads each Coverage contains and not the summed Coverage in a tile region.

correct.

**Comment by DengEr-1993** [comment]
> Hi @DengEr-1993
> 
> > `mincov` means  the least coverage reads in every sample is 3 , not in all samples simutaneously, is that right ?
> 
> it is the minimum read coverage to be included in the methylKit objects. Any methylated base/region in the text files below the mincov value will be ignored. this holds true for **every** sample.
> 
> > By the way, if I use mincov = 5 here,  or 3 as you said,  then if it is not necessary for me to  do filterByCoverage (myobj, lo.count = 5) then ?
> 
> not necessarily. You might need to include this step when reading tabix files though, since they are not filtered but directly loaded.
> 
> > If I set mincov=5 at the first step, here filterByCoverage(lo.count = 5)  has the same function, right ?
> 
> yes.
> 
> > A small question: here I set  win.size = 500, step.size = 500, is that ok? Because I want a 500bp window. But I don’t know the difference between win.size and step.size.
> 
> yes, this should work. `win.size` sets the size of each window, `step.size` sets how far the next window will be shifted relative to previous one. if `step.size` is smaller than `win.size` you will get overlapping tiles .
> 
> > Finally, I understand the cov.bases(), it means the number of CpG sites in a specific window (tile region). So there must be more than 5 CpG sites but not  how many reads each Coverage contains and not the summed Coverage in a tile region.
> 
> correct.

@alexg9010 ,  thank you very much. I have understand most key points.

You helped me a lot. 

Thank you for you quick response. 

Have a nice day. 

Best,
xiangyi
