### ISSUE TITLE
Is it necessary that using normalization before doing dmr calling ?

### ISSUE THREAD

**Issue by DengEr-1993** [al2na/methylKit#294]

**Comment by DengEr-1993** [comment]
Hi @alexg9010 ,

A small question about dmr calling.


I read the tutorial [here ](https://bioconductor.org/packages/devel/bioc/vignettes/methylKit/inst/doc/methylKit.html#34_Batch_effects) before 

[6.0.7 Should I normalize my data ?](https://bioconductor.org/packages/devel/bioc/vignettes/methylKit/inst/doc/methylKit.html#34_Batch_effects)


It means that it is better to do normalization before dmr calling.

I don't know if I don't do this step, is that ok ?


Best,
xiangyi

**Comment by alexg9010** [comment]
Hi @DengEr-1993,

Normalisation is required if your samples are showing large differences in their coverage distribution. are

**Comment by DengEr-1993** [comment]
@alexg9010  Thanks !
