### ISSUE TITLE
possible typo in `methCall.pl`

### ISSUE THREAD

**Issue by CathG** [al2na/methylKit#30]
When performing a `paired_sam` analysis, `perform_sam` subroutine is called but the 2 last parameters (`nolap` and `paired`) are inverted compared to their positions in `perform_sam` definition: the value of `nolap` is used to set parameter `paired`.

**Comment by al2na** [comment]
I'm closing this, as this is fixed in dev version and also generally works as commented here https://github.com/al2na/methylKit/pull/31
