### ISSUE TITLE
Annotate DMRs with .gff files?

### ISSUE THREAD

**Issue by Ge0rges** [al2na/methylKit#301]
Hello,

I was wondering if it's possible to annotate the genomes being analyzed using the standard [GFF](https://www.ensembl.org/info/website/upload/gff.html?redirect=no) format? This format is used by popular annotation tools such as Prodigal and Prokka.

Thanks

**Comment by alexg9010** [comment]
Hi @Ge0rges 

There is some code available to achieve this:  https://github.com/BIMSBbioinfo/genomation/issues/192 .

Best,
Alex

**Comment by Ge0rges** [comment]
This was posted on the google forum after finding that referenced issue. I closed this to minimize duplication. Ref: https://groups.google.com/g/methylkit_discussion/c/Hyk-PsEWsac
