### ISSUE TITLE
error in getTargetAnnotationStats

### ISSUE THREAD

**Issue by Kaustav-93** [al2na/methylKit#306]
Hi,

This is how my diffAnn df looks like and I am getting this error

head(getAssociationWithTSS(diffAnn))
     target.row dist.to.feature         feature.name feature.strand
11            1             118 ENSMUST00000192183.1              +
14            2             -94 ENSMUST00000070533.4              -
14.1          3             -99 ENSMUST00000070533.4              -
14.2          4            -489 ENSMUST00000070533.4              -
16            5          -18679 ENSMUST00000194454.1              +
26            6            1200 ENSMUST00000192505.1              -
getTargetAnnotationStats(diffAnn,percentage=TRUE,precedence=TRUE)

Error in getTargetAnnotationStats(diffAnn, percentage = TRUE, precedence = TRUE) : 
  unused arguments (diffAnn, percentage = TRUE, precedence = TRUE)

Thanks for you help in advance

**Comment by jyotikat2025** [comment]
@mbanuh thanks! seriously saved my day! was thinking totally beyond the box and it turned out to be this simple issue but do you mind telling what goes wrong sometimes as per your experience? I have experienced this in rmarkdown rendering most of the times.
