### ISSUE TITLE
The deep theory of calculateDiffMeth() function of MethylKit

### ISSUE THREAD

**Issue by DengEr-1993** [al2na/methylKit#307]
Hello there,

I have a question about calculateDiffMeth() function in package MethylKit that I used it to do differential RRBS analysis but I am not so familiar with its deep theory.

Because I just want to know how does the` calculateDiffMeth()` calculate or compare the difference between treatment and control groups.

I referred to the tutorial of methylKit and it said: _Depending on the sample size per each set it will either use Fisher’s exact or logistic regression to calculate P-values. P-values will be adjusted to Q-values using [SLIM method](http://www.ncbi.nlm.nih.gov/pubmed/21098430)_ but I didn't get it in some degree.

For example,  I have two groups with two replicates, respectively, treatment and control.

Then, I should convert CpGs to tiles with different window size, such as 500bp or 1000bp with definite filtering conditions. 

But when running `myDiff=calculateDiffMeth(meth)` this step on **tiling window**
I want to know the difference between treatment and control is based on the total CpG sites percentage (sum(freqC)/sum(Coverage)) of methylation level region or on the mean CpG sites percentage (mean(freqC)/mean(Coverage)) of the methylation level region ?

For this question, if not, if there is any other extra calculation theory such as scaling or normalization that may change the original value?

Because I visualized the dmr calling results from MethylKit via pheatmap and then I want to see this results in CpG results via IGV.
But the two visualization methods didn't show us quite consistent result. 

So could you give me some advice or how to explain this question ?

Thanks a lot.

Best,
xiangyi

**Comment by DengEr-1993** [comment]
Hello Alex,

Thank you very much for your response. 

Yes, we double checked our result that was the same to our original CpG data and  just as you said above, I think I can understand the theory totally. 

The reason why I post this question is because we want to see details of CpGs in IGV.  

In IGV, we found that  CpG sites of zero methylation level wouldn't be showed via bars. Some of us thought the same positions of one replicate sample were not detected by RRBS. So we might believe some of our RRBS data is of poor quality. But now we think our data is ok. 

Now it is quite clear.  Thanks again.

Have a nice day.


Best,
xiangyi

**Comment by alexg9010** [comment]
Another idea of how you could explore your results in IGV would be to export your objects as bedgraph files using the [bedgraph() function](https://www.rdocumentation.org/packages/methylKit/versions/0.99.2/topics/bedgraph). 

You could export the methDiff objects using `meth.diff` column to visualize methylation difference as done in the [original paper](https://genomebiology.biomedcentral.com/articles/10.1186/gb-2012-13-10-r87/figures/5). 

Usually in IGV, exploring the samples via the bismark bam files you should see coverage and methylation percentage just fine, but you could also create different bedgraph files from the methylRaw/methylRawList objects. Just explore the option of the bedgraph() function. 

Best,
Alex

**Comment by DengEr-1993** [comment]
> Another idea of how you could explore your results in IGV would be to export your objects as bedgraph files using the [bedgraph() function](https://www.rdocumentation.org/packages/methylKit/versions/0.99.2/topics/bedgraph).
> 
> You could export the methDiff objects using `meth.diff` column to visualize methylation difference as done in the [original paper](https://genomebiology.biomedcentral.com/articles/10.1186/gb-2012-13-10-r87/figures/5).
> 
> Usually in IGV, exploring the samples via the bismark bam files you should see coverage and methylation percentage just fine, but you could also create different bedgraph files from the methylRaw/methylRawList objects. Just explore the option of the bedgraph() function.
> 
> Best, Alex

Thanks for your advice. Have a nice day.
