### ISSUE TITLE
MethylKit and Methylation Data from PacBio sequence

### ISSUE THREAD

**Issue by olaraym** [al2na/methylKit#308]
Hi @al2na, I wanted to inquire if MethylKit package can be used to run Differential methylation analysis for methylation call data obtained from hifi reads.

**Comment by DavYang** [comment]
Hi @al2na , I recently came across[ your section](https://compgenomr.github.io/book/extracting-interesting-regions-differential-methylation-and-segmentation.html#methylation-segmentation) on segmentation and differential methylation analysis and was curious about the same thing.

**Comment by alexg9010** [comment]
Hi @olaraym and @DavYang,

I did not work with hifi-reads / pacBio data myself, but the `methRead` function supports reading generic file types via the `pipeline` argument. You may check the details and examples of the [`methRead` help](https://www.rdocumentation.org/packages/methylKit/versions/0.99.2/topics/methRead). 

So, if you can get per-base methylation call data (probably using [pb-CpG-tools](https://github.com/PacificBiosciences/pb-CpG-tools)?) you should be able to import this into methylKit. 

@DavYang One thing that you have to consider is that methylKit was not designed with long reads in mind, so especially for segmentation or haplotype-aware analysis you may be better off using a tool supporting read-level-based analysis, such as [pycometh for ONT](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-023-02917-w#Fig3) or [ccsmethphase for PacBio](https://www.nature.com/articles/s41467-023-39784-9#Fig4).

I hope this helps, but if you have more general questions please also consider posting them on the [discussion forum](https://groups.google.com/g/methylkit_discussion). 

Best,
Alex
