### ISSUE TITLE
One question about DMR calling between single sample in one group versus replicated sample in another group

### ISSUE THREAD

**Issue by DengEr-1993** [al2na/methylKit#314]
Hello alexg9010,

I want to confirm one thing that I referred to your article here: [methylKit: a comprehensive R package for the analysis of genome-wide DNA methylation profiles](url) and you said there we can do dmr calling between two groups in which group may have one sample.

_when there is one sample per group, Fisher’s exact test will be used._ 

But if I have several groups **(A, B, C, D, E, F)**, each group has more than two replicates. But only one group **(for example, F)** has only single sample. 
And then I do dmr calling between two groups from all my groups. 

The questions is  when dmr calling between A or B or C or D or E versus F (single-sample group) or reversely F versus A or B or C or D or E,  can I do dmr calling directly ? Should I do something adjustment on script ?

Thanks in advance.

Looking forward to your response. 

Best regards,
Xiangyi

**Comment by alexg9010** [comment]
Hi @DengEr-1993 ,

As you mentioned, Fisher's exact test will only be performed when there is **exactly** one sample per group. 
This means if **any** of the two groups that are compared against each other have more than one sample `calculateDiffmeth` will switch to Chisq-test. This can be seen here, where we check for exactly two samples, i.e. one sample per group:
https://github.com/al2na/methylKit/blob/0a5581c33accb8493f00658325fc1d8c4a6370c8/R/diffMeth.R#L570

If you want to force the function to run Fisher's Exact test, you should `pool()` samples within groups to a single sample per group before running the test. 

Best
Alex

**Comment by alexg9010** [comment]
Hi @DengEr-1993 ,

You can directly run the function, it should just work. 

Best
Alex

**Comment by DengEr-1993** [comment]
> Hi @DengEr-1993 ,
> 
> You can directly run the function, it should just work.
> 
> Best Alex

Thanks !
