### ISSUE TITLE
MethylationStats shows one peak

### ISSUE THREAD

**Issue by gevro** [al2na/methylKit#317]
Hi, My methylationstats profile doesn't look like what is in the vignette. Is this a computational issue or does this suggest a specific sample issue?

Thanks
<img width="738" alt="Screenshot 2024-03-13 at 8 29 01 PM" src="https://github.com/al2na/methylKit/assets/47928628/a807d3c7-dd09-49b4-a272-7cf00e763c4a">

**Comment by alexg9010** [comment]
Hi @gevro,

if there were no errors when importing your data I assume it is a sample-specific issue.
Could you provide further details about the data source and the sample?

You should probably also consult the person who generated the data, to see if this is expected. 

Best
Alex

**Comment by gevro** [comment]
It is a bisulfite RRBS WGS sample. Is this simply an indication of low conversion efficiency?

**Comment by alexg9010** [comment]
Hi @gevro

The methylation percentage pattern for RRBS is different than the one for WGBS.  RRBS targets sites with high CpG density, e.g. CpG islands, which are usually highly methylated. WGBS covers the whole genome including areas with low CpG density, which are usually lowly methylated. 

See https://www.illumina.com/science/sequencing-method-explorer/kits-and-arrays/rrbs-seq-scrrbs.html

Best
Alex

**Comment by gevro** [comment]
Sorry, I meant to write it is WGBS. Is this pattern abnormal for WGBS?

**Comment by alexg9010** [comment]
Hi @gevro,

This depends on the organism that you are studying. For mammals, the normal pattern would be a bimodal distribution for CpG and very low methylation for non-CpG sites, like in the vignette. On the other hand, for plants, you would expect a different pattern where also non-CpG sites are methylated (see [here](https://journals.plos.org/plosgenetics/article/figure?id=10.1371/journal.pgen.1006526.g001)).

Best
Alex

**Comment by gevro** [comment]
Thanks!
