### ISSUE TITLE
error：Calls: calculateDiffMeth ... simplify2array -> mclapply -> lapply -> FUN -> mcfork

### ISSUE THREAD

**Issue by changchuanjun** [al2na/methylKit#318]
Hello! Thank you for your contribution on methylKit. When I run my script, I meet a problem. Do you know how to solve it?
my command is :

> Rscript  [methylation.R](https://github.com/al2na/methylKit/files/14823326/methylation.txt) --samples_file sample.txt --contrasts contrasts.txt --fmt calmeth --context CHH --window 600 -                                     -step 200 --threads 2 -o CHH_result --dm dmr

the error is :
Error in lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...) :
  没有(非NA)案例可用
Calls: calculateDiffMeth ... p.adjusted -> QValuesfun -> SLIMfunc -> lm -> lm.fit
此外: Warning message:
In mclapply(cntlist, logReg, vars, treatment = treatment, overdispersion = overdispersion,  :
  scheduled core 1 did not deliver a result, all values of the job will be affected
停止执行

**Comment by alexg9010** [comment]
HI @changchuanjun ,

When translating the error message to English it says that there are `No (non-NA) cases available`. 

This indicates NA values in your data are causing the failure of `calculateDiffMeth`. Some people reported fixing the problem by removing NA values first (https://github.com/al2na/methylKit/issues/206#issuecomment-1303220254). 

Best,
Alex

**Comment by changchuanjun** [comment]
@alexg9010 ,thank you for your reply
