### ISSUE TITLE
 tileMethylCounts(mrl_base, win.size=600,step.size=200,cov.bases = 4

### ISSUE THREAD

**Issue by yhj-j** [al2na/methylKit#320]
Hello, when I report an error in DMR analysis, how should I solve this problem?

run de analysis for leaf vs Root , context: CHH
Received list of locations.
Reading file.
Reading file.
Reading file.
Reading file.
Error in h(simpleError(msg, call)) :
  error in evaluating the argument 'x' in selecting a method for function 'as.matrix': cannot allocate vector of size 4.3 Gb
Calls: tileMethylCounts ... findOverlaps_GNCList -> <Anonymous> -> .Call2 -> .handleSimpleError -> h
Execution halted
Warning message:
system call failed: Cannot allocate memory

**Comment by alexg9010** [comment]
The error is indicating that your memory/RAM is not sufficient. 
You could try to run the analysis using methylDB objects, which are stored on disk. Please see sections 2.2, 5.2 and 5.3 of the user guide for more information. 

Best, 
Alex
