### ISSUE TITLE
Error: The sam file is not sorted properly on positions

### ISSUE THREAD

**Issue by iranianuser** [al2na/methylKit#330]
Hello
I m using methylkit on bismark alignment files. I used the command below and used the bam output from bismark alignment process:
`methRaw = processBismarkAln( location = "/media/genome2/SP PHD U3/vahedi/802/SRR4298802_1_val_1_bismark_bt2_pe.bam", sample.id="Cancer_802", assembly = "hg38", treatment = (1), read.context = "CpG")`
 I have 3 cancerous samples and 1 control but first I test just one of my samples. 
 I got this Error :`The sam file is not sorted properly on positions:	chr: 11  pos: 36283681 is followed by chr: 11  pos: 36283418 
You can sort the file in unix-like machines using:
 grep -v \'^[[:space:]]*\@\' test.sam | sort -k3,3 -k4,4n  > test.sorted.sam `

what can I do to solve this problem??

thanks alot

**Comment by alexg9010** [comment]
To fix this error you should sort the bam 
file via samtools.

Best,
Alex

**Comment by iranianuser** [comment]
thank you for your response. Do you think that the below process is okay:
bismark alignment (bam.file)-----sort bam-----deduplicate sort bam----index deduplicated sort bam---bismark methylation extractor to get cov file-----finaly the data is ready to analysis with methylkit.

**Comment by alexg9010** [comment]
Yes, this should work. However please note that the coverage file does not
include stand information. If this is relevant, you may use the cytosine
report instead.

Saeedeh ***@***.***> schrieb am Fr., 4. Okt. 2024, 10:59:

**Comment by iranianuser** [comment]
I'm really confused. Should I convert the coverage file to a cytosine report and then use the cytosine report for methylkit analysis? 
and another problem is when I sort the bam file by chromosome position, deduplication process failed with this error:
`Now testing Bismark result file /home/genome2/Desktop/vahedi/Bismark-0.24.2/805bam/sorted_805.bam for positional sorting (which would be bad...)	
The IDs of Read 1 (SRR4298805.132253926_HISEQ:202:C5K5EACXX:4:2212:2015:45771_length=100) and Read 2 (SRR4298805.128532228_HISEQ:202:C5K5EACXX:4:2210:8388:64080_length=100) are not the same. This might be a result of sorting the paired-end SAM/BAM files by chromosomal position which is not compatible with correct methylation extraction. Please use an unsorted file instead (e.g. use samtools sort -n)
`  
May be, we should do the sorting process at another time because the deduplication and extraction need the sorted bam file by name.

please guide me

**Comment by alexg9010** [comment]
There are two different routes to take when you want to get bismark output
into methylkit.

Approach 1, is the one that you started this issue with. You take a
**sorted** bismark bam file and run processBismarkAln. The bam file can be
deduplicated, but it has to be sorted afterwards.

Approach 2, would be as you listed in your last response (
https://github.com/al2na/methylKit/issues/330#issuecomment-2393200840), but
I think there is no sorting step  required if you go this route. Then you
read in the cytosine report or coverage file using methRead by adjusting
the pipeline argument.

The cytosine report can be generated using the bismark methylation
extractor, see the last command in their docs (
https://felixkrueger.github.io/Bismark/bismark/methylation_extraction/) or
via their coverage2cytosine script.
Best,
Alex




Saeedeh ***@***.***> schrieb am Fr., 4. Okt. 2024, 13:42:

**Comment by iranianuser** [comment]
Yes, I thought the cytosine report is the best because of its structure. but when I used this file I got an error:

`Error in `[.data.frame`(data, , 6) : undefined columns selected`

I check my data:

`> head(read.table("/media/genome2/SP PHD U3/cov/cleaned_data802.txt", header=FALSE))
          V1 V2 V3 V4 V5
1 KI270539.1  7  +  0  0
2 KI270539.1  8  -  0  0
3 KI270539.1 11  +  0  0
4 KI270539.1 12  -  0  0
5 KI270539.1 51  +  0  0
6 KI270539.1 52  -  0  0`

this was my data which was include chromosome, posithion, strand, unM and M

however, as you mentioned, I'll try sorted bam file with "processBismarkAln" function and let you know the result.

thanks a lot

**Comment by iranianuser** [comment]
sorry this is the cytosine report:

 V1 V2 V3 V4 V5
1 KI270539.1  7  +  0  0
2 KI270539.1  8  -  0  0
3 KI270539.1 11  +  0  0
4 KI270539.1 12  -  0  0
5 KI270539.1 51  +  0  0
6 KI270539.1 52  -  0  0

**Comment by alexg9010** [comment]
This does not seem like the right file, the format is described here:
https://felixkrueger.github.io/Bismark/bismark/methylation_extraction/#optional-genome-wide-cytosine-report-output

Saeedeh ***@***.***> schrieb am Sa., 5. Okt. 2024, 07:01:

**Comment by iranianuser** [comment]
Hi Alex, 
I followed the first method you mentioned. First, I deduplicated the BAM file, then I sorted the deduplicated file, and after sorting, I indexed it. Finally, I used the sorted file for the `processBismarkAln` function. The steps went smoothly without any errors, and I successfully identified the DMRs. 
Thanks for your guidance!
I just have one question: Is performing normalization, batch effect correction, and correlation analysis also essential for statistical analyses? (Since nothing about them was mentioned in this protocol = https://bioinformaticsdotca.github.io/EPI_2021_Module4_lab#r_import  ).

**Comment by alexg9010** [comment]
Hi,
great to hear you managed to analyse your data.
I would say the correlation plot is not essential, but the other steps may
be required if you observe batch effects or large coverage differences in
your data.

Saeedeh ***@***.***> schrieb am So., 13. Okt. 2024, 18:02:
