### ISSUE TITLE
How do the annotateWithFeatureFlank and annotateWithGeneParts functions output meta-information of CpG sites?

### ISSUE THREAD

**Issue by QuietgraceH** [al2na/methylKit#335]
This is a very good tool. I encountered some problems when using the annotateWithFeatureFlank function and the annotateWithGeneParts function. I can get the proportional results, but I want to get and output the CpG site information belonging to promoter/exon/intron or annotated as CpGi/shores. How can I get it? I look forward to your reply.

Best,
jingya

**Comment by alexg9010** [comment]
Hi @QuietgraceH,

You may use the `getMembers()` function from genomation, this gives you a matrix showing overlap of target features with annotation features. 1 for overlap, 0 for non-overlap. 

```
library(methylKit)
library(genomation)
data(methylKit)

cpg.obj=readFeatureFlank(system.file("extdata", "cpgi.hg18.bed.txt", 
                                        package = "methylKit"),
                           feature.flank.name=c("CpGi","shores"))

diffCpGann=annotateWithFeatureFlank(as(methylDiff.obj, "GRanges"),
                                    cpg.obj$CpGi,cpg.obj$shores,
                         feature.name="CpGi",flank.name="shores")

genomation::getMembers(diffCpGann)
```

Best, 
Alex
