### ISSUE TITLE
calculateDiffMeth: Incorrect input format for fast.fisher

### ISSUE THREAD

**Issue by huwenhuo** [al2na/methylKit#35]
In diffMeth.R

I guess this come from  these:
  set1.Cs=.Object@numCs.index[.Object@treatment==1]
    set2.Cs=.Object@numCs.index[.Object@treatment==0]
    set1.Ts=.Object@numTs.index[.Object@treatment==1]
    set2.Ts=.Object@numTs.index[.Object@treatment==0]

treatment usually is 1 and 2, rather 0 and 1.

**Comment by al2na** [comment]
Treatment is 0,1 where did you see that example ? All the documentation
suggests 0,1

On Monday, 21 March 2016, huwenhuo <notifications@github.com> wrote:

> In diffMeth.R
>
> I guess this come from these:
> set1.Cs=.Object@numCs.index
> <javascript:_e(%7B%7D,'cvml','.Object@numCs.index');>[.Object@treatment
> ==1]
> set2.Cs=.Object@numCs.index
> <javascript:_e(%7B%7D,'cvml','.Object@numCs.index');>[.Object@treatment
> ==0]
> set1.Ts=.Object@numTs.index
> <javascript:_e(%7B%7D,'cvml','.Object@numTs.index');>[.Object@treatment
> ==1]
> set2.Ts=.Object@numTs.index
> <javascript:_e(%7B%7D,'cvml','.Object@numTs.index');>[.Object@treatment
> ==0]
>
> treatment usually is 1 and 2, rather 0 and 1.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/al2na/methylKit/issues/35>
>


-- 
Sent from mobile, excuse the brevity

**Comment by huwenhuo** [comment]
I just put a factor vector of two elements as treatment which translate to 1, 2. I didn't check carefully with the manual though. Thanks.

**Comment by al2na** [comment]
I think it is 0,1 only and it is documented. It should work for any factor variable that has two levels or vectors with two unique values in an ideal world. But in that case, we should add another argument to determine what is compared to what when getting methylation difference, with 0, 1 encoding that is documented. So, I'm closing this for now.
