### ISSUE TITLE
the new version looks great but I get an error message when I try to install:

### ISSUE THREAD

**Issue by cgrunau** [al2na/methylKit#40]
* installing *source* package ‘methylKit’ ...
** libs
make: Nothing to be done for `all'.
installing to /Library/Frameworks/R.framework/Versions/3.3/Resources/library/methylKit/libs
** R
** data
** inst
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Library/Frameworks/R.framework/Versions/3.3/Resources/library/methylKit/libs/methylKit.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.3/Resources/library/methylKit/libs/methylKit.so, 6): Library not loaded: /Users/aakalin/Rlibs/Rhtslib/lib/libhts.0.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.3/Resources/library/methylKit/libs/methylKit.so
  Reason: image not found
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/methylKit’
Error: Command failed (1)

**Comment by al2na** [comment]
Can you try to install Rhtslib from the source then retry? Did you try to
install as instructed in the README.md ?

On Thursday, 2 June 2016, cgrunau <notifications@github.com> wrote:

>
>    - installing *source* package ‘methylKit’ ... ** libs make: Nothing to
>    be done for `all'. installing to
>    /Library/Frameworks/R.framework/Versions/3.3/Resources/library/methylKit/libs
>    ** R ** data ** inst ** tests ** preparing package for lazy loading ** help
>    *** installing help indices ** building package indices ** installing
>    vignettes ** testing if installed package can be loaded Error in
>    dyn.load(file, DLLpath = DLLpath, ...) : unable to load shared object
>    '/Library/Frameworks/R.framework/Versions/3.3/Resources/library/methylKit/libs/methylKit.so':
>    dlopen(/Library/Frameworks/R.framework/Versions/3.3/Resources/library/methylKit/libs/methylKit.so,
>    6): Library not loaded: /Users/aakalin/Rlibs/Rhtslib/lib/libhts.0.dylib
>    Referenced from:
>    /Library/Frameworks/R.framework/Versions/3.3/Resources/library/methylKit/libs/methylKit.so
>    Reason: image not found Error: loading failed Execution halted ERROR:
>    loading failed
>    - removing
>    ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/methylKit’
>    Error: Command failed (1)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/al2na/methylKit/issues/40>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAm9EfrqAtvPff8UCLmLscB4IPmwhWjmks5qHv--gaJpZM4IsuE9>
> .
>


-- 
Sent from mobile, excuse the brevity

**Comment by DarwinAwardWinner** [comment]
I'm seeing a similar error on Ubuntu 16.04, R 3.3.0:

```
> library(devtools)
> install_github("al2na/methylKit", build_vignettes=FALSE, 
+   repos=BiocInstaller::biocinstallRepos(),
+   dependencies=TRUE, type
type.convert  typeof        
+   dependencies=TRUE, type="source")
Downloading GitHub repo al2na/methylKit@master
from URL https://api.github.com/repos/al2na/methylKit/zipball/master
Installing methylKit
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet  \
  CMD INSTALL '/tmp/RtmpSrPeFO/devtools547b1ad44451/al2na-methylKit-02e2273'  \
  --library='/home/ryan/R/x86_64-pc-linux-gnu-library/3.3' --install-tests 

* installing *source* package ‘methylKit’ ...
** libs
make: Nothing to be done for 'all'.
installing to /home/ryan/R/x86_64-pc-linux-gnu-library/3.3/methylKit/libs
** R
** data
** inst
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/home/ryan/R/x86_64-pc-linux-gnu-library/3.3/methylKit/libs/methylKit.so':
  /home/ryan/R/x86_64-pc-linux-gnu-library/3.3/methylKit/libs/methylKit.so: invalid ELF header
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/ryan/R/x86_64-pc-linux-gnu-library/3.3/methylKit’
Error: Command failed (1)
```

**Comment by DarwinAwardWinner** [comment]
Is it normal to have a .so file checked into version control? Doesn't this file need to be recompiled for every system?

**Comment by DarwinAwardWinner** [comment]
After downloading and unpacking the package and then deleting the .o and .so files, the package installed successfully. the `file` command said they were `Mach-O 64-bit x86_64 object` and `Mach-O 64-bit x86_64 dynamically linked shared library`, which are Mac OS object files which should not be present when installing on Linux.

**Comment by al2na** [comment]
just saw the comments, yes .so and .o shouldn't be there. Somehow R studio doesn't show it in the file pane but they are there and created during check. Now I deleted them, and installation works as expected for couple of other people. I'm closing this, please report back if the problem persists.

**Comment by DarwinAwardWinner** [comment]
FYI you should probably add `*.so` and `*.o` to your `.gitignore` files to prevent this in the future.
