### ISSUE TITLE
diffMethPerChr percentages

### ISSUE THREAD

**Issue by igordot** [al2na/methylKit#44]
After calling `diffMethPerChr()`, the percentages of hypermethylated and hypomethylated add up to over 100. Is that a bug or a misunderstanding?

Example:
```
> diffMethPerChr = diffMethPerChr(mkDiff, plot=F, qvalue.cutoff=1.0, meth.cutoff=0)
> diffMethPerChr
$diffMeth.per.chr
     chr number.of.hypermethylated percentage.of.hypermethylated number.of.hypomethylated percentage.of.hypomethylated
1   chr1                      1043                      51.27827                     1110                     54.57227
12  chr2                      1489                      51.88153                     1549                     53.97213
13  chr3                       846                      52.71028                      858                     53.45794
14  chr4                      1314                      50.36412                     1408                     53.96704
```

**Comment by al2na** [comment]
I think meth.cutoff uses >= so things that are 0 % different might be
counted twice ?

On Wednesday, 29 June 2016, igor <notifications@github.com> wrote:

> After calling diffMethPerChr(), the percentages of hypermethylated and
> hypomethylated add up to over 100. Is that a bug or a misunderstanding?
>
> Example:
>
> > diffMethPerChr = diffMethPerChr(mkDiff, plot=F, qvalue.cutoff=1.0, meth.cutoff=0)
> > diffMethPerChr
> $diffMeth.per.chr
>      chr number.of.hypermethylated percentage.of.hypermethylated number.of.hypomethylated percentage.of.hypomethylated
> 1   chr1                      1043                      51.27827                     1110                     54.57227
> 12  chr2                      1489                      51.88153                     1549                     53.97213
> 13  chr3                       846                      52.71028                      858                     53.45794
> 14  chr4                      1314                      50.36412                     1408                     53.96704
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/al2na/methylKit/issues/44>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAm9EcJP5I61f_ckuE23c37YRB-rpFevks5qQbv8gaJpZM4JAqbM>
> .
>


-- 
Sent from mobile, excuse the brevity

**Comment by igordot** [comment]
I think you're right. Switching to `meth.cutoff=0.00001` changed the values. Now the total is ~95%. Apparently there are a lot of sites with difference of 0.

Is there a better to get a number of hyper/hypo sites per chromosome without any cutoff?

**Comment by al2na** [comment]
why don't you use meth.cutoff=0.00001 and a lower p-value cutoff? There has
to be at least a sensible q-value cutoff such as 0.05 or 0.1. if the
difference between methylation values are 0 or close to 0 they are not
differentially methylated anyway, so using a very small meth.cutoff
shouldn't be a problem
