### ISSUE TITLE
libtool error in the installation of methykit

### ISSUE THREAD

**Issue by Baffort** [al2na/methylKit#45]
Dear al2na,

I have installed the latest R and bioclite, but there were libtool error when I were installing methykit package by using your install_github code in R console. The detailed error information is attached below, thanks for your help.

Error information:
../libtool: line 5986: cd: :/ifshk1/BC_CANCER/03user/lixiangchun/Software/INSTALL/hdf5-1.8.16/lib:/ifshk4/BC_PUB/biosoft/PIPE_RD/Package/R-3.1.1/lib64/R/lib:/ifshk1/BC_CANCER/03user/lixiangchun/Software/INSTALL/zlib-1.2.8/lib:/ifshk1/BC_CANCER/03user/lixiangchun/Software/INSTALL/bzip2-1.0.6/lib:/ifshk7/BC_RES/TECH/PMO/zhangbaifeng/eDMR/xz/lib:/ifshk7/BC_RES/TECH/PMO/zhangbaifeng/eDMR/pcre/lib:/ifshk7/BC_RES/TECH/PMO/zhangbaifeng/eDMR/pcre-8.39/curl/lib: No such file or directory 
libtool: link: cannot determine absolute directory name of `:/ifshk1/BC_CANCER/03user/lixiangchun/Software/INSTALL/hdf5-1.8.16/lib:/ifshk4/BC_PUB/biosoft/PIPE_RD/Package/R-3.1.1/lib64/R/lib:/ifshk1/BC_CANCER/03user/lixiangchun/Software/INSTALL/zlib-1.2.8/lib:/ifshk1/BC_CANCER/03user/lixiangchun/Software/INSTALL/bzip2-1.0.6/lib:/ifshk7/BC_RES/TECH/PMO/zhangbaifeng/eDMR/xz/lib:/ifshk7/BC_RES/TECH/PMO/zhangbaifeng/eDMR/pcre/lib:/ifshk7/BC_RES/TECH/PMO/zhangbaifeng/eDMR/pcre-8.39/curl/lib' 
make[5]: *** [libgnu.la] Error 1 
make[5]: Leaving directory `/tmp/RtmpfLBspx/devtools7c1c1c4ee618/Rhtslib/src/htslib/lib' 
make[4]: *** [all-recursive] Error 1 
make[4]: Leaving directory `/tmp/RtmpfLBspx/devtools7c1c1c4ee618/Rhtslib/src/htslib/lib' 
make[3]: *** [all] Error 2 
make[3]: Leaving directory `/tmp/RtmpfLBspx/devtools7c1c1c4ee618/Rhtslib/src/htslib/lib' 
make[2]: *** [all-recursive] Error 1 
make[2]: Leaving directory `/tmp/RtmpfLBspx/devtools7c1c1c4ee618/Rhtslib/src/htslib' 
make[1]: *** [all] Error 2 
make[1]: Leaving directory `/tmp/RtmpfLBspx/devtools7c1c1c4ee618/Rhtslib/src/htslib' 
make: *** [htslib/libhts.la] Error 2 
ERROR: compilation failed for package 'Rhtslib' 
* removing '/ifshk7/BC_RES/TECH/PMO/zhangbaifeng/eDMR/R-3.3.1/library/Rhtslib' 
Error: Command failed (1)

**Comment by al2na** [comment]
I replied to this over at methylKit_discussion
