### ISSUE TITLE
is it ok to load bismark CpG_report files with non-integer counts?

### ISSUE THREAD

**Issue by avilella** [al2na/methylKit#48]
Hi,

I am inputting CpG_report.txt.gz oxBS and BS bismark files into
methpipe mlml, which uses an EM algorithm to determine the levels of
5-mC and 5-hmC by subtracting the converted and non-converted counts
from the oxBS and BS experiments. This produces three coefficients for
each position, namely:

1. 5-mC level
2. 5-hmC level
3. unmethylated level

After this process, I can produce two output files in
CpG_report.txt.gz format which due to the EM algorithm above, will
sometimes produce counts that are non-integer. E.g. for columns 4th and 5th in Bismark CpG_report.txt.gz:

```
The genome-wide cytosine methylation output file is tab-delimited in the following format:
==========================================================================================
<chromosome>  <position>  <strand>  <count methylated>  <count non-methylated>  <C-context>  <trinucleotide context>
```

Given a position with coverage 56, and the following 5-mC, 5-hmC and C
levels, columns 4th and 5th would be non-integers:

```
0.483333*56 = 27.066648
0.416667*56 = 23.333352
0.1*56      = 5.6
-----------------------
1.0*56      = 56
```

I think the adjust.methylC function may be doing a similar
manipulation to the counts, and the result is also loaded as a
`methylRaw` object, but I want to make sure what I am doing here is
kosher.

```R
# adjusting the 5mC levels using 5hmC levels
adjusted.5mC=adjustMethylC(my5mC,my5hmC)
```

I would like to make sure that methylKit can ingest this non-integer
CpG_report.txt.gz file correctly, and one still will be able to use
the minimum coverage option to filter out low-coverage positions to do
the DMR calling.

I am using the readBismarkCytosineReport function as described below.

Let me know if this is a good way to proceed.

```R
#' Read bismark cytosine report file as a methylKit object
#' 
#' Bismark aligner can output methylation information per base in
#' multiple different formats. This function reads cytosine report files,
#' which have chr,start, strand, number of cytosines (methylated bases) 
#' and number of thymines (unmethylated bases),context, trinucletide context.
#' 
#' \@param location a list or vector of file paths to coverage files
#'     
#' \@param sample.id a list or vector of sample ids
#' \@param assembly a string for genome assembly. Any string would work.
#' \@param treatment if there are multiple files to be read a treatment 
#'                  vector should be supplied.
#' \@param context a string for context of methylation such as: "CpG" or "CHG"
#' \@param min.cov a numeric value for minimum coverage. Bases that have coverage
#' below this value will be removed.
#' 
#' \@return methylRaw or methylRawList objects

readBismarkCytosineReport<-function(location,sample.id,assembly="unknown",treatment,
                                         context="CpG",min.cov=10){
  if(length(location)>1){
    stopifnot(length(location)==length(sample.id),
              length(location)==length(treatment))
  }
  
  result=list()
  for(i in 1:length(location)){
    df=fread.gzipped(location[[i]],data.table=FALSE)
    
    # remove low coverage stuff
    df=df[ (df[,4]+df[,5]) >= min.cov ,]
    
    
    
    
    # make the object (arrange columns of df), put it in a list
    result[[i]]= new("methylRaw",
                     data.frame(chr=df[,1],start=df[,2],end=df[,2],
                                strand=df[,3],coverage=(df[,4]+df[,5]),
                                numCs=df[,4],numTs=df[,5]),
                     sample.id=sample.id[[i]],
                     assembly=assembly,context=context,resolution="base"
    )
  }
  
  if(length(result) == 1){
    return(result[[1]])
  }else{
    
    new("methylRawList",result,treatment=treatment)
  }
}
```

**Comment by al2na** [comment]
Hi Albert,
Off the top of my head this will work. If somehow it doesn't you can always
transform floating numbers to nearest integers using round() in R.

I have a plan to implement that EM algorithm in methylKit but didn't come
to it yet.

Best,
altuna
