### ISSUE TITLE
build errors in Bioconductor methylKit devel version

### ISSUE THREAD

**Issue by adeschen** [al2na/methylKit#58]
Hi,

We are developing two R packages that are using the Bioconductor version of methylKit. We plan to submit our packages to Bioconductor. However, the development version of the methylKit package (Bioconductor 3.5) has some build errors: http://bioconductor.org/checkResults/devel/bioc-LATEST/methylKit/. Those errors are related to functions that have been removed from the IRanges devel package. I have noticed that most functions are not used anymore by methylKit. So, by removing those importations, the problem should be solved.

I wonder if this issue is currently being processed.

Thanks,

Astrid

**Comment by al2na** [comment]
Hi, You can use the latest github version (1.1.6) for development, I removed that import. I will push this bioc-devel as soon as I can.

Best,
Altuna

**Comment by adeschen** [comment]
Thank you for your quick reply.

Best regards,
Astrid

**Comment by al2na** [comment]
v 1.1.6 is on BioC-devel and passes the check
