### ISSUE TITLE
methRead reads all C types ?

### ISSUE THREAD

**Issue by hxlei** [al2na/methylKit#61]
I've been using methylKit recently. It's easy to use.
Here is my question.When I use methRead to read bismarkCytosineReport( I used --cytosine_report --CX. So the report is mixed with CpG, CHH and CHG ), I get methylRaw object mixed with the three kinds of C. 

Here is my command.
meth=methRead(sample_list,
          sample.id=list("test","ctrl"),
          assembly="hg19",
          treatment=c(1,0),
          context="CpG",
          pipeline = "bismarkCytosineReport",
          header=FALSE,
          mincov = 1)

I thought  _context_ argument can filter CHH & CHG at first. Now it seems wrong. Am I right ?  I think should seperate them before read in R.

**Comment by al2na** [comment]
Hi,
context argument is there for book keeping purposes. The user has to
provide correct files for the context of interest. You can also ask such
questions in the discussion forum

https://groups.google.com/forum/#!forum/methylkit_discussion

Best,
Altuna
