### ISSUE TITLE
failed installation, S4Vectors update

### ISSUE THREAD

**Issue by timedreamer** [al2na/methylKit#66]
Hello,
 I tired to install based on manual with:

`library(devtools)
install_github("al2na/methylKit", build_vignettes=FALSE, 
               repos=BiocInstaller::biocinstallRepos(),
               dependencies=TRUE,type="source")
`
But I got this:

`Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace ‘S4Vectors’ 0.12.2 is already loaded, but >= 0.13.13 is required
ERROR: lazy loading failed for package ‘methylKit’`

I also tried to update **S4Vectors** with: 

`source("https://bioconductor.org/biocLite.R")
biocLite("S4Vectors")`

But the version I got is 0.12.2, I think that's the latest stable version. How do I install version >=0.13.13? 

I guess I'm not the only one with this question, you may consider add it in the installation manaul.

Thanks!

Ji

**Comment by timedreamer** [comment]
Never mind. I think I was install developement version, used Bioconductor and it works fine. You can close this now.

Thank you.

`source("https://bioconductor.org/biocLite.R")
biocLite("methylKit")`

**Comment by al2na** [comment]
you can also use 1.1.7BioC3.4 branch which should work with the current BioC
