### ISSUE TITLE
Problem with `percMethylation` function

### ISSUE THREAD

**Issue by sameet** [al2na/methylKit#68]
Hi,
I was trying to use the `percMethylation` function to create a data-frame of percent methylation values.  However, I got the following error:
    '''
    > class(united.obj)
    [1] "methylBaseDB"
    attr(,"package")
    [1] "methylKit"
    > mat <- percMethylation(united.obj)
    Error in rbindlist(res) :
      Item 1 of list input is not a data.frame, data.table or list
    '''

When I looked at the code, and trying to generate the same using `getData()`, and then the `numCs.index`, and `numTs.index`, it worked.

**Comment by al2na** [comment]
which version are you using?

**Comment by al2na** [comment]
reopen and provide more info if this is still a problem
