### ISSUE TITLE
tileMethylCounts and missing data

### ISSUE THREAD

**Issue by karl616** [al2na/methylKit#71]
Hi,

we are currently happy to use MethylKit in our group.

Still, a small issue with tileMethylCounts. One of my colleagues noticed that tileMethylCounts generated a lot of NA-tiles when min.per.group was lower than the number of samples. She was able to identify that it was enough with a single missing value to have it propagated into the associated tile. Is this a design decision?

We followed it up and landed in the regionCounts function. It looks like the sums are done without excluding NA-values. I attach a small patch with the beginning to a fix. It isn't tested and I suspect it might not be complete. This "fix" has the potential to generate a variable number of tiles per sample and I didn't understand how the merging worked. There could be a problem

[methylKit.relaxedTiling.patch.txt](https://github.com/al2na/methylKit/files/902654/methylKit.relaxedTiling.patch.txt)

**Comment by al2na** [comment]
I'm not sure how this can fix the bug. If NA values are a problem, that should occur after the unite function. Do you should edit the function that works on methylBase objects. It would also be great if you can do a proper pull request after you make sure that the bug is fixed.

**Comment by karl616** [comment]
OK, thanks. I'm not very versed in the S4 ways of things. 

It is not so much the NA values as such that is the problem as the way they work with the tiling. If there is a single missing value for a tile in a sample, the whole tile is considered missing although the cov.bases requirement would still be fulfilled. A counter-argument I could see is that this ensures that all compared tiles contain the same sites.

I'll be out of office next week, but I'll see what I can do when I come back.

**Comment by al2na** [comment]
If you are worried about missing values, another way would be to do tiling
on methylRaw objects and use unite() afterwards. This way you would ensure
that tiles are not dropped due to NA values.

Best,
Altuna
