### ISSUE TITLE
concern about p-values of zero

### ISSUE THREAD

**Issue by KatSchulze** [al2na/methylKit#75]
Hi,

Our lab has been using methylKit for the differential methylation analysis of our 13 bisulfite sequencing samples (7 cases, 6 controls;  without covariates but with coverage normalization) and noticed that for a couple of sites we were receiving p-values of zero, as seen in this example:

chr    start           end            strand   pvalue               qvalue                 meth.diff
chr1  11160205  11160205   +           4.780530e-04   0.033563177        -15.166690
chr1  11336239  11336239   +           9.241583e-04   0.048401063        6.739688
**chr1  11396931  11396931   +           0.000000e+00  0.000000000        -43.781785**
chr1  11398012  11398012    -           2.156598e-05   0.005130648        14.402332
chr1  11561902  11561902    -           3.546179e-06   0.001508041        28.381195

To us, such a p-value seems a bit too good to be true, so we were wondering if you could tell us what would lead to a p-value of zero? Is there, for example, a p-value threshold after the passing of which the output is simply rounded to zero? Or might there be another artifact that could be causing this?

Thanks for your time and an otherwise great tool!

**Comment by al2na** [comment]
They are not probably exactly 0 but looks like 0 due to machine precision.
I wouldn't worry too much about them.
https://stackoverflow.com/questions/6970705/why-cant-i-get-a-p-value-smaller-than-2-2e-16

I also recommend trying overdispersion correction with
overdispersion="MN",test="Chisq"
 arguments.

**Comment by KatSchulze** [comment]
Good to know - thanks a bunch! I'll give the overdispersion correction a try
