### ISSUE TITLE
Error While Annotating DMRs

### ISSUE THREAD

**Issue by VivekTodur** [al2na/methylKit#76]
Hi, I am following the tutorial provided, on executing the following command, I am getting an error. Could you please help me in resolving this issue.

**gene.obj=readTranscriptFeatures(system.file("extdata", "refseq.hg18.bed.txt", package = "methylKit"))**

Reading the table...
Calculating intron coordinates...
Error in (function (cl, name, valueClass)  : 
  assignment of an object of class "NULL" is not valid for @'NAMES' in an object of class "IRanges"; is(value, "characterORNULL") is not TRUE

**Comment by al2na** [comment]
update the BioC and R to the latest versions and reopen this ticket it the
problem persists

**Comment by VivekTodur** [comment]
Thanks, Issue resolved...
