### ISSUE TITLE
Header in tabix file

### ISSUE THREAD

**Issue by alexg9010** [al2na/methylKit#89]
storing extra information in tabix files is actually quite easy:

```
#load library
library(methylKit)

# load table stored in tabix file
my_mat <- headTabix("inst/extdata/ctrl2.txt.bgz")


# write comment-header to new file
write(x = "#ctrl2.txt.bgz","../my_file.txt")
# write table to new file
write.table(x = my_mat,file = "../my_file.txt",
            append = TRUE,col.names = FALSE,
            row.names = FALSE,sep = "\t")

# make tabix out of file
makeMethTabix("../my_file.txt",rm.file = FALSE)

# view table stored in tabix file
headTabix("../my_file.txt.bgz")

# access other information of tabix file
Rsamtools::headerTabix("../my_file.txt.bgz")

# especially header
Rsamtools::headerTabix("../my_file.txt.bgz")$header
```

Maybe it would also be a good idea to store all slots of a methylDB object in its tabix file, such that we can easily reread all information.

**Comment by al2na** [comment]
just to re-iterate for future versions of ourselves, by doing this all the necessary info for a methylKit object will be stored in a tabix file without any R data component, future functions will read the tabix and create all the auxiliary information such as treatment, assembly and sample names from it.
