### ISSUE TITLE
how to find the differential methylation regions?

### ISSUE THREAD

**Issue by lvl2001** [al2na/methylKit#93]
sorry to interrupt again. here I have a question, I use methylkit for my rice BS-seq data analysis, and I can find the differential methylated cytosine using calculateDiffMeth code, but I am confused to how to get the DMR? I try through the whole command and did't get the satisifying result?  I used the eDMR to analysis my data and only found "CpG" context sequences analyzed, how about the "CHH" "CHG"? how can I get my rice data pass the analysis?
Thanks a lot and looling forward to hear from you!

**Comment by al2na** [comment]
ask about eDMR to the maintainer for eDMR, this is not the right place.
what you need to do should be possible but I'm not entirely sure.
