### ISSUE TITLE
Implement method to combine methylRaw objects  

### ISSUE THREAD

**Issue by alexg9010** [al2na/methylKit#98]
In some situations it might be convenient to have a function to combine multiple methylRaw objects into a methylRawList object. 

something like:

```
methylRawList <- function(...,treatment) {

## check if treatment has same length as number of inputs 

## check if input is really of type methylRaw 

## just merge if valid

    mrl <- new("methylRawList", list(...), treatment)
   if(valid.methylRawList(mrl)) return(mrl)
}
```

**Comment by al2na** [comment]
you can use new() to do that, but I see the point for making it easier on
users.

**Comment by alexg9010** [comment]
I was just thinking about this, because for the diffmeth report we are having multiple methylRaw objects at hand, but no exported method to merge those.
