### ISSUE TITLE
fix getSampleID for diffMeth objects

### ISSUE THREAD

**Issue by alexg9010** [al2na/methylKit#99]
https://github.com/al2na/methylKit/blob/master/R/diffMeth.R#L905

**Comment by alexg9010** [comment]
```
> getSampleID(methylDiff)
Error in getSampleID(methylDiff) : 
  no slot of name "sample.id" for this object of class "methylDiff"
```

**Comment by al2na** [comment]
should there be sample ids for methylDiff? I guess it is useful to keep
track of the samples that are used to create methylDiff
